services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:6.2
    container_name: redis
    environment:
      - TZ=${DB_TZ}
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    restart: unless-stopped