// Code generated by ent, DO NOT EDIT.

package consentlog

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the consentlog type in the database.
	Label = "consent_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldClientConsentID holds the string denoting the client_consent_id field in the database.
	FieldClientConsentID = "client_consent_id"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldConsentType holds the string denoting the consent_type field in the database.
	FieldConsentType = "consent_type"
	// FieldPolicyVersion holds the string denoting the policy_version field in the database.
	FieldPolicyVersion = "policy_version"
	// FieldGranted holds the string denoting the granted field in the database.
	FieldGranted = "granted"
	// FieldNickname holds the string denoting the nickname field in the database.
	FieldNickname = "nickname"
	// FieldConsentedAt holds the string denoting the consented_at field in the database.
	FieldConsentedAt = "consented_at"
	// FieldClientVersion holds the string denoting the client_version field in the database.
	FieldClientVersion = "client_version"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldLocale holds the string denoting the locale field in the database.
	FieldLocale = "locale"
	// FieldBuildMode holds the string denoting the build_mode field in the database.
	FieldBuildMode = "build_mode"
	// FieldReceivedAt holds the string denoting the received_at field in the database.
	FieldReceivedAt = "received_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// Table holds the table name of the consentlog in the database.
	Table = "consent_logs"
)

// Columns holds all SQL columns for consentlog fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldClientConsentID,
	FieldClientID,
	FieldUserID,
	FieldConsentType,
	FieldPolicyVersion,
	FieldGranted,
	FieldNickname,
	FieldConsentedAt,
	FieldClientVersion,
	FieldPlatform,
	FieldLocale,
	FieldBuildMode,
	FieldReceivedAt,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// PolicyVersionValidator is a validator for the "policy_version" field. It is called by the builders before save.
	PolicyVersionValidator func(string) error
	// NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	NicknameValidator func(string) error
	// ClientVersionValidator is a validator for the "client_version" field. It is called by the builders before save.
	ClientVersionValidator func(string) error
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// LocaleValidator is a validator for the "locale" field. It is called by the builders before save.
	LocaleValidator func(string) error
	// BuildModeValidator is a validator for the "build_mode" field. It is called by the builders before save.
	BuildModeValidator func(string) error
	// DefaultReceivedAt holds the default value on creation for the "received_at" field.
	DefaultReceivedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// ConsentType defines the type for the "consent_type" enum field.
type ConsentType string

// ConsentType values.
const (
	ConsentTypeEula    ConsentType = "eula"
	ConsentTypePrivacy ConsentType = "privacy"
)

func (ct ConsentType) String() string {
	return string(ct)
}

// ConsentTypeValidator is a validator for the "consent_type" field enum values. It is called by the builders before save.
func ConsentTypeValidator(ct ConsentType) error {
	switch ct {
	case ConsentTypeEula, ConsentTypePrivacy:
		return nil
	default:
		return fmt.Errorf("consentlog: invalid enum value for consent_type field: %q", ct)
	}
}

// OrderOption defines the ordering options for the ConsentLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByClientConsentID orders the results by the client_consent_id field.
func ByClientConsentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientConsentID, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByConsentType orders the results by the consent_type field.
func ByConsentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsentType, opts...).ToFunc()
}

// ByPolicyVersion orders the results by the policy_version field.
func ByPolicyVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPolicyVersion, opts...).ToFunc()
}

// ByGranted orders the results by the granted field.
func ByGranted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGranted, opts...).ToFunc()
}

// ByNickname orders the results by the nickname field.
func ByNickname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNickname, opts...).ToFunc()
}

// ByConsentedAt orders the results by the consented_at field.
func ByConsentedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsentedAt, opts...).ToFunc()
}

// ByClientVersion orders the results by the client_version field.
func ByClientVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientVersion, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByLocale orders the results by the locale field.
func ByLocale(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocale, opts...).ToFunc()
}

// ByBuildMode orders the results by the build_mode field.
func ByBuildMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuildMode, opts...).ToFunc()
}

// ByReceivedAt orders the results by the received_at field.
func ByReceivedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReceivedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}
