// Code generated by ent, DO NOT EDIT.

package consentlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/witchs-lounge_backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// ClientConsentID applies equality check predicate on the "client_consent_id" field. It's identical to ClientConsentIDEQ.
func ClientConsentID(v uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldClientConsentID, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldClientID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldUserID, v))
}

// PolicyVersion applies equality check predicate on the "policy_version" field. It's identical to PolicyVersionEQ.
func PolicyVersion(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldPolicyVersion, v))
}

// Granted applies equality check predicate on the "granted" field. It's identical to GrantedEQ.
func Granted(v bool) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldGranted, v))
}

// Nickname applies equality check predicate on the "nickname" field. It's identical to NicknameEQ.
func Nickname(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldNickname, v))
}

// ConsentedAt applies equality check predicate on the "consented_at" field. It's identical to ConsentedAtEQ.
func ConsentedAt(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldConsentedAt, v))
}

// ClientVersion applies equality check predicate on the "client_version" field. It's identical to ClientVersionEQ.
func ClientVersion(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldClientVersion, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldPlatform, v))
}

// Locale applies equality check predicate on the "locale" field. It's identical to LocaleEQ.
func Locale(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldLocale, v))
}

// BuildMode applies equality check predicate on the "build_mode" field. It's identical to BuildModeEQ.
func BuildMode(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldBuildMode, v))
}

// ReceivedAt applies equality check predicate on the "received_at" field. It's identical to ReceivedAtEQ.
func ReceivedAt(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldReceivedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLTE(FieldUpdatedAt, v))
}

// ClientConsentIDEQ applies the EQ predicate on the "client_consent_id" field.
func ClientConsentIDEQ(v uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldClientConsentID, v))
}

// ClientConsentIDNEQ applies the NEQ predicate on the "client_consent_id" field.
func ClientConsentIDNEQ(v uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNEQ(FieldClientConsentID, v))
}

// ClientConsentIDIn applies the In predicate on the "client_consent_id" field.
func ClientConsentIDIn(vs ...uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldIn(FieldClientConsentID, vs...))
}

// ClientConsentIDNotIn applies the NotIn predicate on the "client_consent_id" field.
func ClientConsentIDNotIn(vs ...uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNotIn(FieldClientConsentID, vs...))
}

// ClientConsentIDGT applies the GT predicate on the "client_consent_id" field.
func ClientConsentIDGT(v uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGT(FieldClientConsentID, v))
}

// ClientConsentIDGTE applies the GTE predicate on the "client_consent_id" field.
func ClientConsentIDGTE(v uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGTE(FieldClientConsentID, v))
}

// ClientConsentIDLT applies the LT predicate on the "client_consent_id" field.
func ClientConsentIDLT(v uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLT(FieldClientConsentID, v))
}

// ClientConsentIDLTE applies the LTE predicate on the "client_consent_id" field.
func ClientConsentIDLTE(v uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLTE(FieldClientConsentID, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLTE(FieldClientID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNotNull(FieldUserID))
}

// ConsentTypeEQ applies the EQ predicate on the "consent_type" field.
func ConsentTypeEQ(v ConsentType) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldConsentType, v))
}

// ConsentTypeNEQ applies the NEQ predicate on the "consent_type" field.
func ConsentTypeNEQ(v ConsentType) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNEQ(FieldConsentType, v))
}

// ConsentTypeIn applies the In predicate on the "consent_type" field.
func ConsentTypeIn(vs ...ConsentType) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldIn(FieldConsentType, vs...))
}

// ConsentTypeNotIn applies the NotIn predicate on the "consent_type" field.
func ConsentTypeNotIn(vs ...ConsentType) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNotIn(FieldConsentType, vs...))
}

// PolicyVersionEQ applies the EQ predicate on the "policy_version" field.
func PolicyVersionEQ(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldPolicyVersion, v))
}

// PolicyVersionNEQ applies the NEQ predicate on the "policy_version" field.
func PolicyVersionNEQ(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNEQ(FieldPolicyVersion, v))
}

// PolicyVersionIn applies the In predicate on the "policy_version" field.
func PolicyVersionIn(vs ...string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldIn(FieldPolicyVersion, vs...))
}

// PolicyVersionNotIn applies the NotIn predicate on the "policy_version" field.
func PolicyVersionNotIn(vs ...string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNotIn(FieldPolicyVersion, vs...))
}

// PolicyVersionGT applies the GT predicate on the "policy_version" field.
func PolicyVersionGT(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGT(FieldPolicyVersion, v))
}

// PolicyVersionGTE applies the GTE predicate on the "policy_version" field.
func PolicyVersionGTE(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGTE(FieldPolicyVersion, v))
}

// PolicyVersionLT applies the LT predicate on the "policy_version" field.
func PolicyVersionLT(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLT(FieldPolicyVersion, v))
}

// PolicyVersionLTE applies the LTE predicate on the "policy_version" field.
func PolicyVersionLTE(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLTE(FieldPolicyVersion, v))
}

// PolicyVersionContains applies the Contains predicate on the "policy_version" field.
func PolicyVersionContains(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldContains(FieldPolicyVersion, v))
}

// PolicyVersionHasPrefix applies the HasPrefix predicate on the "policy_version" field.
func PolicyVersionHasPrefix(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldHasPrefix(FieldPolicyVersion, v))
}

// PolicyVersionHasSuffix applies the HasSuffix predicate on the "policy_version" field.
func PolicyVersionHasSuffix(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldHasSuffix(FieldPolicyVersion, v))
}

// PolicyVersionEqualFold applies the EqualFold predicate on the "policy_version" field.
func PolicyVersionEqualFold(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEqualFold(FieldPolicyVersion, v))
}

// PolicyVersionContainsFold applies the ContainsFold predicate on the "policy_version" field.
func PolicyVersionContainsFold(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldContainsFold(FieldPolicyVersion, v))
}

// GrantedEQ applies the EQ predicate on the "granted" field.
func GrantedEQ(v bool) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldGranted, v))
}

// GrantedNEQ applies the NEQ predicate on the "granted" field.
func GrantedNEQ(v bool) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNEQ(FieldGranted, v))
}

// NicknameEQ applies the EQ predicate on the "nickname" field.
func NicknameEQ(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldNickname, v))
}

// NicknameNEQ applies the NEQ predicate on the "nickname" field.
func NicknameNEQ(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNEQ(FieldNickname, v))
}

// NicknameIn applies the In predicate on the "nickname" field.
func NicknameIn(vs ...string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldIn(FieldNickname, vs...))
}

// NicknameNotIn applies the NotIn predicate on the "nickname" field.
func NicknameNotIn(vs ...string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNotIn(FieldNickname, vs...))
}

// NicknameGT applies the GT predicate on the "nickname" field.
func NicknameGT(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGT(FieldNickname, v))
}

// NicknameGTE applies the GTE predicate on the "nickname" field.
func NicknameGTE(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGTE(FieldNickname, v))
}

// NicknameLT applies the LT predicate on the "nickname" field.
func NicknameLT(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLT(FieldNickname, v))
}

// NicknameLTE applies the LTE predicate on the "nickname" field.
func NicknameLTE(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLTE(FieldNickname, v))
}

// NicknameContains applies the Contains predicate on the "nickname" field.
func NicknameContains(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldContains(FieldNickname, v))
}

// NicknameHasPrefix applies the HasPrefix predicate on the "nickname" field.
func NicknameHasPrefix(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldHasPrefix(FieldNickname, v))
}

// NicknameHasSuffix applies the HasSuffix predicate on the "nickname" field.
func NicknameHasSuffix(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldHasSuffix(FieldNickname, v))
}

// NicknameIsNil applies the IsNil predicate on the "nickname" field.
func NicknameIsNil() predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldIsNull(FieldNickname))
}

// NicknameNotNil applies the NotNil predicate on the "nickname" field.
func NicknameNotNil() predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNotNull(FieldNickname))
}

// NicknameEqualFold applies the EqualFold predicate on the "nickname" field.
func NicknameEqualFold(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEqualFold(FieldNickname, v))
}

// NicknameContainsFold applies the ContainsFold predicate on the "nickname" field.
func NicknameContainsFold(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldContainsFold(FieldNickname, v))
}

// ConsentedAtEQ applies the EQ predicate on the "consented_at" field.
func ConsentedAtEQ(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldConsentedAt, v))
}

// ConsentedAtNEQ applies the NEQ predicate on the "consented_at" field.
func ConsentedAtNEQ(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNEQ(FieldConsentedAt, v))
}

// ConsentedAtIn applies the In predicate on the "consented_at" field.
func ConsentedAtIn(vs ...time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldIn(FieldConsentedAt, vs...))
}

// ConsentedAtNotIn applies the NotIn predicate on the "consented_at" field.
func ConsentedAtNotIn(vs ...time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNotIn(FieldConsentedAt, vs...))
}

// ConsentedAtGT applies the GT predicate on the "consented_at" field.
func ConsentedAtGT(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGT(FieldConsentedAt, v))
}

// ConsentedAtGTE applies the GTE predicate on the "consented_at" field.
func ConsentedAtGTE(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGTE(FieldConsentedAt, v))
}

// ConsentedAtLT applies the LT predicate on the "consented_at" field.
func ConsentedAtLT(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLT(FieldConsentedAt, v))
}

// ConsentedAtLTE applies the LTE predicate on the "consented_at" field.
func ConsentedAtLTE(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLTE(FieldConsentedAt, v))
}

// ClientVersionEQ applies the EQ predicate on the "client_version" field.
func ClientVersionEQ(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldClientVersion, v))
}

// ClientVersionNEQ applies the NEQ predicate on the "client_version" field.
func ClientVersionNEQ(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNEQ(FieldClientVersion, v))
}

// ClientVersionIn applies the In predicate on the "client_version" field.
func ClientVersionIn(vs ...string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldIn(FieldClientVersion, vs...))
}

// ClientVersionNotIn applies the NotIn predicate on the "client_version" field.
func ClientVersionNotIn(vs ...string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNotIn(FieldClientVersion, vs...))
}

// ClientVersionGT applies the GT predicate on the "client_version" field.
func ClientVersionGT(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGT(FieldClientVersion, v))
}

// ClientVersionGTE applies the GTE predicate on the "client_version" field.
func ClientVersionGTE(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGTE(FieldClientVersion, v))
}

// ClientVersionLT applies the LT predicate on the "client_version" field.
func ClientVersionLT(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLT(FieldClientVersion, v))
}

// ClientVersionLTE applies the LTE predicate on the "client_version" field.
func ClientVersionLTE(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLTE(FieldClientVersion, v))
}

// ClientVersionContains applies the Contains predicate on the "client_version" field.
func ClientVersionContains(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldContains(FieldClientVersion, v))
}

// ClientVersionHasPrefix applies the HasPrefix predicate on the "client_version" field.
func ClientVersionHasPrefix(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldHasPrefix(FieldClientVersion, v))
}

// ClientVersionHasSuffix applies the HasSuffix predicate on the "client_version" field.
func ClientVersionHasSuffix(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldHasSuffix(FieldClientVersion, v))
}

// ClientVersionIsNil applies the IsNil predicate on the "client_version" field.
func ClientVersionIsNil() predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldIsNull(FieldClientVersion))
}

// ClientVersionNotNil applies the NotNil predicate on the "client_version" field.
func ClientVersionNotNil() predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNotNull(FieldClientVersion))
}

// ClientVersionEqualFold applies the EqualFold predicate on the "client_version" field.
func ClientVersionEqualFold(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEqualFold(FieldClientVersion, v))
}

// ClientVersionContainsFold applies the ContainsFold predicate on the "client_version" field.
func ClientVersionContainsFold(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldContainsFold(FieldClientVersion, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformIsNil applies the IsNil predicate on the "platform" field.
func PlatformIsNil() predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldIsNull(FieldPlatform))
}

// PlatformNotNil applies the NotNil predicate on the "platform" field.
func PlatformNotNil() predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNotNull(FieldPlatform))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldContainsFold(FieldPlatform, v))
}

// LocaleEQ applies the EQ predicate on the "locale" field.
func LocaleEQ(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldLocale, v))
}

// LocaleNEQ applies the NEQ predicate on the "locale" field.
func LocaleNEQ(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNEQ(FieldLocale, v))
}

// LocaleIn applies the In predicate on the "locale" field.
func LocaleIn(vs ...string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldIn(FieldLocale, vs...))
}

// LocaleNotIn applies the NotIn predicate on the "locale" field.
func LocaleNotIn(vs ...string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNotIn(FieldLocale, vs...))
}

// LocaleGT applies the GT predicate on the "locale" field.
func LocaleGT(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGT(FieldLocale, v))
}

// LocaleGTE applies the GTE predicate on the "locale" field.
func LocaleGTE(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGTE(FieldLocale, v))
}

// LocaleLT applies the LT predicate on the "locale" field.
func LocaleLT(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLT(FieldLocale, v))
}

// LocaleLTE applies the LTE predicate on the "locale" field.
func LocaleLTE(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLTE(FieldLocale, v))
}

// LocaleContains applies the Contains predicate on the "locale" field.
func LocaleContains(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldContains(FieldLocale, v))
}

// LocaleHasPrefix applies the HasPrefix predicate on the "locale" field.
func LocaleHasPrefix(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldHasPrefix(FieldLocale, v))
}

// LocaleHasSuffix applies the HasSuffix predicate on the "locale" field.
func LocaleHasSuffix(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldHasSuffix(FieldLocale, v))
}

// LocaleIsNil applies the IsNil predicate on the "locale" field.
func LocaleIsNil() predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldIsNull(FieldLocale))
}

// LocaleNotNil applies the NotNil predicate on the "locale" field.
func LocaleNotNil() predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNotNull(FieldLocale))
}

// LocaleEqualFold applies the EqualFold predicate on the "locale" field.
func LocaleEqualFold(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEqualFold(FieldLocale, v))
}

// LocaleContainsFold applies the ContainsFold predicate on the "locale" field.
func LocaleContainsFold(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldContainsFold(FieldLocale, v))
}

// BuildModeEQ applies the EQ predicate on the "build_mode" field.
func BuildModeEQ(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldBuildMode, v))
}

// BuildModeNEQ applies the NEQ predicate on the "build_mode" field.
func BuildModeNEQ(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNEQ(FieldBuildMode, v))
}

// BuildModeIn applies the In predicate on the "build_mode" field.
func BuildModeIn(vs ...string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldIn(FieldBuildMode, vs...))
}

// BuildModeNotIn applies the NotIn predicate on the "build_mode" field.
func BuildModeNotIn(vs ...string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNotIn(FieldBuildMode, vs...))
}

// BuildModeGT applies the GT predicate on the "build_mode" field.
func BuildModeGT(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGT(FieldBuildMode, v))
}

// BuildModeGTE applies the GTE predicate on the "build_mode" field.
func BuildModeGTE(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGTE(FieldBuildMode, v))
}

// BuildModeLT applies the LT predicate on the "build_mode" field.
func BuildModeLT(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLT(FieldBuildMode, v))
}

// BuildModeLTE applies the LTE predicate on the "build_mode" field.
func BuildModeLTE(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLTE(FieldBuildMode, v))
}

// BuildModeContains applies the Contains predicate on the "build_mode" field.
func BuildModeContains(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldContains(FieldBuildMode, v))
}

// BuildModeHasPrefix applies the HasPrefix predicate on the "build_mode" field.
func BuildModeHasPrefix(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldHasPrefix(FieldBuildMode, v))
}

// BuildModeHasSuffix applies the HasSuffix predicate on the "build_mode" field.
func BuildModeHasSuffix(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldHasSuffix(FieldBuildMode, v))
}

// BuildModeIsNil applies the IsNil predicate on the "build_mode" field.
func BuildModeIsNil() predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldIsNull(FieldBuildMode))
}

// BuildModeNotNil applies the NotNil predicate on the "build_mode" field.
func BuildModeNotNil() predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNotNull(FieldBuildMode))
}

// BuildModeEqualFold applies the EqualFold predicate on the "build_mode" field.
func BuildModeEqualFold(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEqualFold(FieldBuildMode, v))
}

// BuildModeContainsFold applies the ContainsFold predicate on the "build_mode" field.
func BuildModeContainsFold(v string) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldContainsFold(FieldBuildMode, v))
}

// ReceivedAtEQ applies the EQ predicate on the "received_at" field.
func ReceivedAtEQ(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldReceivedAt, v))
}

// ReceivedAtNEQ applies the NEQ predicate on the "received_at" field.
func ReceivedAtNEQ(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNEQ(FieldReceivedAt, v))
}

// ReceivedAtIn applies the In predicate on the "received_at" field.
func ReceivedAtIn(vs ...time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldIn(FieldReceivedAt, vs...))
}

// ReceivedAtNotIn applies the NotIn predicate on the "received_at" field.
func ReceivedAtNotIn(vs ...time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNotIn(FieldReceivedAt, vs...))
}

// ReceivedAtGT applies the GT predicate on the "received_at" field.
func ReceivedAtGT(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGT(FieldReceivedAt, v))
}

// ReceivedAtGTE applies the GTE predicate on the "received_at" field.
func ReceivedAtGTE(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGTE(FieldReceivedAt, v))
}

// ReceivedAtLT applies the LT predicate on the "received_at" field.
func ReceivedAtLT(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLT(FieldReceivedAt, v))
}

// ReceivedAtLTE applies the LTE predicate on the "received_at" field.
func ReceivedAtLTE(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLTE(FieldReceivedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.ConsentLog {
	return predicate.ConsentLog(sql.FieldNotNull(FieldExpiresAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ConsentLog) predicate.ConsentLog {
	return predicate.ConsentLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ConsentLog) predicate.ConsentLog {
	return predicate.ConsentLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ConsentLog) predicate.ConsentLog {
	return predicate.ConsentLog(sql.NotPredicates(p))
}
