// Code generated by ent, DO NOT EDIT.

package record

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/witchs-lounge_backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldUserID, v))
}

// MusicID applies equality check predicate on the "music_id" field. It's identical to MusicIDEQ.
func MusicID(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldMusicID, v))
}

// StageID applies equality check predicate on the "stage_id" field. It's identical to StageIDEQ.
func StageID(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldStageID, v))
}

// Score applies equality check predicate on the "score" field. It's identical to ScoreEQ.
func Score(v int) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldScore, v))
}

// PerfectCount applies equality check predicate on the "perfect_count" field. It's identical to PerfectCountEQ.
func PerfectCount(v int) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldPerfectCount, v))
}

// GoodCount applies equality check predicate on the "good_count" field. It's identical to GoodCountEQ.
func GoodCount(v int) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldGoodCount, v))
}

// BadCount applies equality check predicate on the "bad_count" field. It's identical to BadCountEQ.
func BadCount(v int) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldBadCount, v))
}

// MissCount applies equality check predicate on the "miss_count" field. It's identical to MissCountEQ.
func MissCount(v int) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldMissCount, v))
}

// MaxCombo applies equality check predicate on the "max_combo" field. It's identical to MaxComboEQ.
func MaxCombo(v int) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldMaxCombo, v))
}

// Accuracy applies equality check predicate on the "accuracy" field. It's identical to AccuracyEQ.
func Accuracy(v float64) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldAccuracy, v))
}

// IsFullCombo applies equality check predicate on the "is_full_combo" field. It's identical to IsFullComboEQ.
func IsFullCombo(v bool) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldIsFullCombo, v))
}

// IsPerfectPlay applies equality check predicate on the "is_perfect_play" field. It's identical to IsPerfectPlayEQ.
func IsPerfectPlay(v bool) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldIsPerfectPlay, v))
}

// IsValid applies equality check predicate on the "is_valid" field. It's identical to IsValidEQ.
func IsValid(v bool) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldIsValid, v))
}

// ClientRecordID applies equality check predicate on the "client_record_id" field. It's identical to ClientRecordIDEQ.
func ClientRecordID(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldClientRecordID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldUserID, vs...))
}

// MusicIDEQ applies the EQ predicate on the "music_id" field.
func MusicIDEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldMusicID, v))
}

// MusicIDNEQ applies the NEQ predicate on the "music_id" field.
func MusicIDNEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldMusicID, v))
}

// MusicIDIn applies the In predicate on the "music_id" field.
func MusicIDIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldMusicID, vs...))
}

// MusicIDNotIn applies the NotIn predicate on the "music_id" field.
func MusicIDNotIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldMusicID, vs...))
}

// MusicIDGT applies the GT predicate on the "music_id" field.
func MusicIDGT(v string) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldMusicID, v))
}

// MusicIDGTE applies the GTE predicate on the "music_id" field.
func MusicIDGTE(v string) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldMusicID, v))
}

// MusicIDLT applies the LT predicate on the "music_id" field.
func MusicIDLT(v string) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldMusicID, v))
}

// MusicIDLTE applies the LTE predicate on the "music_id" field.
func MusicIDLTE(v string) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldMusicID, v))
}

// MusicIDContains applies the Contains predicate on the "music_id" field.
func MusicIDContains(v string) predicate.Record {
	return predicate.Record(sql.FieldContains(FieldMusicID, v))
}

// MusicIDHasPrefix applies the HasPrefix predicate on the "music_id" field.
func MusicIDHasPrefix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasPrefix(FieldMusicID, v))
}

// MusicIDHasSuffix applies the HasSuffix predicate on the "music_id" field.
func MusicIDHasSuffix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasSuffix(FieldMusicID, v))
}

// MusicIDEqualFold applies the EqualFold predicate on the "music_id" field.
func MusicIDEqualFold(v string) predicate.Record {
	return predicate.Record(sql.FieldEqualFold(FieldMusicID, v))
}

// MusicIDContainsFold applies the ContainsFold predicate on the "music_id" field.
func MusicIDContainsFold(v string) predicate.Record {
	return predicate.Record(sql.FieldContainsFold(FieldMusicID, v))
}

// StageIDEQ applies the EQ predicate on the "stage_id" field.
func StageIDEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldStageID, v))
}

// StageIDNEQ applies the NEQ predicate on the "stage_id" field.
func StageIDNEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldStageID, v))
}

// StageIDIn applies the In predicate on the "stage_id" field.
func StageIDIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldStageID, vs...))
}

// StageIDNotIn applies the NotIn predicate on the "stage_id" field.
func StageIDNotIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldStageID, vs...))
}

// StageIDGT applies the GT predicate on the "stage_id" field.
func StageIDGT(v string) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldStageID, v))
}

// StageIDGTE applies the GTE predicate on the "stage_id" field.
func StageIDGTE(v string) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldStageID, v))
}

// StageIDLT applies the LT predicate on the "stage_id" field.
func StageIDLT(v string) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldStageID, v))
}

// StageIDLTE applies the LTE predicate on the "stage_id" field.
func StageIDLTE(v string) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldStageID, v))
}

// StageIDContains applies the Contains predicate on the "stage_id" field.
func StageIDContains(v string) predicate.Record {
	return predicate.Record(sql.FieldContains(FieldStageID, v))
}

// StageIDHasPrefix applies the HasPrefix predicate on the "stage_id" field.
func StageIDHasPrefix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasPrefix(FieldStageID, v))
}

// StageIDHasSuffix applies the HasSuffix predicate on the "stage_id" field.
func StageIDHasSuffix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasSuffix(FieldStageID, v))
}

// StageIDEqualFold applies the EqualFold predicate on the "stage_id" field.
func StageIDEqualFold(v string) predicate.Record {
	return predicate.Record(sql.FieldEqualFold(FieldStageID, v))
}

// StageIDContainsFold applies the ContainsFold predicate on the "stage_id" field.
func StageIDContainsFold(v string) predicate.Record {
	return predicate.Record(sql.FieldContainsFold(FieldStageID, v))
}

// ScoreEQ applies the EQ predicate on the "score" field.
func ScoreEQ(v int) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldScore, v))
}

// ScoreNEQ applies the NEQ predicate on the "score" field.
func ScoreNEQ(v int) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldScore, v))
}

// ScoreIn applies the In predicate on the "score" field.
func ScoreIn(vs ...int) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldScore, vs...))
}

// ScoreNotIn applies the NotIn predicate on the "score" field.
func ScoreNotIn(vs ...int) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldScore, vs...))
}

// ScoreGT applies the GT predicate on the "score" field.
func ScoreGT(v int) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldScore, v))
}

// ScoreGTE applies the GTE predicate on the "score" field.
func ScoreGTE(v int) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldScore, v))
}

// ScoreLT applies the LT predicate on the "score" field.
func ScoreLT(v int) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldScore, v))
}

// ScoreLTE applies the LTE predicate on the "score" field.
func ScoreLTE(v int) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldScore, v))
}

// PerfectCountEQ applies the EQ predicate on the "perfect_count" field.
func PerfectCountEQ(v int) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldPerfectCount, v))
}

// PerfectCountNEQ applies the NEQ predicate on the "perfect_count" field.
func PerfectCountNEQ(v int) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldPerfectCount, v))
}

// PerfectCountIn applies the In predicate on the "perfect_count" field.
func PerfectCountIn(vs ...int) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldPerfectCount, vs...))
}

// PerfectCountNotIn applies the NotIn predicate on the "perfect_count" field.
func PerfectCountNotIn(vs ...int) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldPerfectCount, vs...))
}

// PerfectCountGT applies the GT predicate on the "perfect_count" field.
func PerfectCountGT(v int) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldPerfectCount, v))
}

// PerfectCountGTE applies the GTE predicate on the "perfect_count" field.
func PerfectCountGTE(v int) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldPerfectCount, v))
}

// PerfectCountLT applies the LT predicate on the "perfect_count" field.
func PerfectCountLT(v int) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldPerfectCount, v))
}

// PerfectCountLTE applies the LTE predicate on the "perfect_count" field.
func PerfectCountLTE(v int) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldPerfectCount, v))
}

// GoodCountEQ applies the EQ predicate on the "good_count" field.
func GoodCountEQ(v int) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldGoodCount, v))
}

// GoodCountNEQ applies the NEQ predicate on the "good_count" field.
func GoodCountNEQ(v int) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldGoodCount, v))
}

// GoodCountIn applies the In predicate on the "good_count" field.
func GoodCountIn(vs ...int) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldGoodCount, vs...))
}

// GoodCountNotIn applies the NotIn predicate on the "good_count" field.
func GoodCountNotIn(vs ...int) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldGoodCount, vs...))
}

// GoodCountGT applies the GT predicate on the "good_count" field.
func GoodCountGT(v int) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldGoodCount, v))
}

// GoodCountGTE applies the GTE predicate on the "good_count" field.
func GoodCountGTE(v int) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldGoodCount, v))
}

// GoodCountLT applies the LT predicate on the "good_count" field.
func GoodCountLT(v int) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldGoodCount, v))
}

// GoodCountLTE applies the LTE predicate on the "good_count" field.
func GoodCountLTE(v int) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldGoodCount, v))
}

// BadCountEQ applies the EQ predicate on the "bad_count" field.
func BadCountEQ(v int) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldBadCount, v))
}

// BadCountNEQ applies the NEQ predicate on the "bad_count" field.
func BadCountNEQ(v int) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldBadCount, v))
}

// BadCountIn applies the In predicate on the "bad_count" field.
func BadCountIn(vs ...int) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldBadCount, vs...))
}

// BadCountNotIn applies the NotIn predicate on the "bad_count" field.
func BadCountNotIn(vs ...int) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldBadCount, vs...))
}

// BadCountGT applies the GT predicate on the "bad_count" field.
func BadCountGT(v int) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldBadCount, v))
}

// BadCountGTE applies the GTE predicate on the "bad_count" field.
func BadCountGTE(v int) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldBadCount, v))
}

// BadCountLT applies the LT predicate on the "bad_count" field.
func BadCountLT(v int) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldBadCount, v))
}

// BadCountLTE applies the LTE predicate on the "bad_count" field.
func BadCountLTE(v int) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldBadCount, v))
}

// MissCountEQ applies the EQ predicate on the "miss_count" field.
func MissCountEQ(v int) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldMissCount, v))
}

// MissCountNEQ applies the NEQ predicate on the "miss_count" field.
func MissCountNEQ(v int) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldMissCount, v))
}

// MissCountIn applies the In predicate on the "miss_count" field.
func MissCountIn(vs ...int) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldMissCount, vs...))
}

// MissCountNotIn applies the NotIn predicate on the "miss_count" field.
func MissCountNotIn(vs ...int) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldMissCount, vs...))
}

// MissCountGT applies the GT predicate on the "miss_count" field.
func MissCountGT(v int) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldMissCount, v))
}

// MissCountGTE applies the GTE predicate on the "miss_count" field.
func MissCountGTE(v int) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldMissCount, v))
}

// MissCountLT applies the LT predicate on the "miss_count" field.
func MissCountLT(v int) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldMissCount, v))
}

// MissCountLTE applies the LTE predicate on the "miss_count" field.
func MissCountLTE(v int) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldMissCount, v))
}

// MaxComboEQ applies the EQ predicate on the "max_combo" field.
func MaxComboEQ(v int) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldMaxCombo, v))
}

// MaxComboNEQ applies the NEQ predicate on the "max_combo" field.
func MaxComboNEQ(v int) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldMaxCombo, v))
}

// MaxComboIn applies the In predicate on the "max_combo" field.
func MaxComboIn(vs ...int) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldMaxCombo, vs...))
}

// MaxComboNotIn applies the NotIn predicate on the "max_combo" field.
func MaxComboNotIn(vs ...int) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldMaxCombo, vs...))
}

// MaxComboGT applies the GT predicate on the "max_combo" field.
func MaxComboGT(v int) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldMaxCombo, v))
}

// MaxComboGTE applies the GTE predicate on the "max_combo" field.
func MaxComboGTE(v int) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldMaxCombo, v))
}

// MaxComboLT applies the LT predicate on the "max_combo" field.
func MaxComboLT(v int) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldMaxCombo, v))
}

// MaxComboLTE applies the LTE predicate on the "max_combo" field.
func MaxComboLTE(v int) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldMaxCombo, v))
}

// AccuracyEQ applies the EQ predicate on the "accuracy" field.
func AccuracyEQ(v float64) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldAccuracy, v))
}

// AccuracyNEQ applies the NEQ predicate on the "accuracy" field.
func AccuracyNEQ(v float64) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldAccuracy, v))
}

// AccuracyIn applies the In predicate on the "accuracy" field.
func AccuracyIn(vs ...float64) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldAccuracy, vs...))
}

// AccuracyNotIn applies the NotIn predicate on the "accuracy" field.
func AccuracyNotIn(vs ...float64) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldAccuracy, vs...))
}

// AccuracyGT applies the GT predicate on the "accuracy" field.
func AccuracyGT(v float64) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldAccuracy, v))
}

// AccuracyGTE applies the GTE predicate on the "accuracy" field.
func AccuracyGTE(v float64) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldAccuracy, v))
}

// AccuracyLT applies the LT predicate on the "accuracy" field.
func AccuracyLT(v float64) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldAccuracy, v))
}

// AccuracyLTE applies the LTE predicate on the "accuracy" field.
func AccuracyLTE(v float64) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldAccuracy, v))
}

// RankEQ applies the EQ predicate on the "rank" field.
func RankEQ(v Rank) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldRank, v))
}

// RankNEQ applies the NEQ predicate on the "rank" field.
func RankNEQ(v Rank) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldRank, v))
}

// RankIn applies the In predicate on the "rank" field.
func RankIn(vs ...Rank) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldRank, vs...))
}

// RankNotIn applies the NotIn predicate on the "rank" field.
func RankNotIn(vs ...Rank) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldRank, vs...))
}

// RankIsNil applies the IsNil predicate on the "rank" field.
func RankIsNil() predicate.Record {
	return predicate.Record(sql.FieldIsNull(FieldRank))
}

// RankNotNil applies the NotNil predicate on the "rank" field.
func RankNotNil() predicate.Record {
	return predicate.Record(sql.FieldNotNull(FieldRank))
}

// IsFullComboEQ applies the EQ predicate on the "is_full_combo" field.
func IsFullComboEQ(v bool) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldIsFullCombo, v))
}

// IsFullComboNEQ applies the NEQ predicate on the "is_full_combo" field.
func IsFullComboNEQ(v bool) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldIsFullCombo, v))
}

// IsPerfectPlayEQ applies the EQ predicate on the "is_perfect_play" field.
func IsPerfectPlayEQ(v bool) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldIsPerfectPlay, v))
}

// IsPerfectPlayNEQ applies the NEQ predicate on the "is_perfect_play" field.
func IsPerfectPlayNEQ(v bool) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldIsPerfectPlay, v))
}

// GameStatusEQ applies the EQ predicate on the "game_status" field.
func GameStatusEQ(v GameStatus) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldGameStatus, v))
}

// GameStatusNEQ applies the NEQ predicate on the "game_status" field.
func GameStatusNEQ(v GameStatus) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldGameStatus, v))
}

// GameStatusIn applies the In predicate on the "game_status" field.
func GameStatusIn(vs ...GameStatus) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldGameStatus, vs...))
}

// GameStatusNotIn applies the NotIn predicate on the "game_status" field.
func GameStatusNotIn(vs ...GameStatus) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldGameStatus, vs...))
}

// AdditionalInfoIsNil applies the IsNil predicate on the "additional_info" field.
func AdditionalInfoIsNil() predicate.Record {
	return predicate.Record(sql.FieldIsNull(FieldAdditionalInfo))
}

// AdditionalInfoNotNil applies the NotNil predicate on the "additional_info" field.
func AdditionalInfoNotNil() predicate.Record {
	return predicate.Record(sql.FieldNotNull(FieldAdditionalInfo))
}

// IsValidEQ applies the EQ predicate on the "is_valid" field.
func IsValidEQ(v bool) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldIsValid, v))
}

// IsValidNEQ applies the NEQ predicate on the "is_valid" field.
func IsValidNEQ(v bool) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldIsValid, v))
}

// ClientRecordIDEQ applies the EQ predicate on the "client_record_id" field.
func ClientRecordIDEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldClientRecordID, v))
}

// ClientRecordIDNEQ applies the NEQ predicate on the "client_record_id" field.
func ClientRecordIDNEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldClientRecordID, v))
}

// ClientRecordIDIn applies the In predicate on the "client_record_id" field.
func ClientRecordIDIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldClientRecordID, vs...))
}

// ClientRecordIDNotIn applies the NotIn predicate on the "client_record_id" field.
func ClientRecordIDNotIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldClientRecordID, vs...))
}

// ClientRecordIDGT applies the GT predicate on the "client_record_id" field.
func ClientRecordIDGT(v string) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldClientRecordID, v))
}

// ClientRecordIDGTE applies the GTE predicate on the "client_record_id" field.
func ClientRecordIDGTE(v string) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldClientRecordID, v))
}

// ClientRecordIDLT applies the LT predicate on the "client_record_id" field.
func ClientRecordIDLT(v string) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldClientRecordID, v))
}

// ClientRecordIDLTE applies the LTE predicate on the "client_record_id" field.
func ClientRecordIDLTE(v string) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldClientRecordID, v))
}

// ClientRecordIDContains applies the Contains predicate on the "client_record_id" field.
func ClientRecordIDContains(v string) predicate.Record {
	return predicate.Record(sql.FieldContains(FieldClientRecordID, v))
}

// ClientRecordIDHasPrefix applies the HasPrefix predicate on the "client_record_id" field.
func ClientRecordIDHasPrefix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasPrefix(FieldClientRecordID, v))
}

// ClientRecordIDHasSuffix applies the HasSuffix predicate on the "client_record_id" field.
func ClientRecordIDHasSuffix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasSuffix(FieldClientRecordID, v))
}

// ClientRecordIDIsNil applies the IsNil predicate on the "client_record_id" field.
func ClientRecordIDIsNil() predicate.Record {
	return predicate.Record(sql.FieldIsNull(FieldClientRecordID))
}

// ClientRecordIDNotNil applies the NotNil predicate on the "client_record_id" field.
func ClientRecordIDNotNil() predicate.Record {
	return predicate.Record(sql.FieldNotNull(FieldClientRecordID))
}

// ClientRecordIDEqualFold applies the EqualFold predicate on the "client_record_id" field.
func ClientRecordIDEqualFold(v string) predicate.Record {
	return predicate.Record(sql.FieldEqualFold(FieldClientRecordID, v))
}

// ClientRecordIDContainsFold applies the ContainsFold predicate on the "client_record_id" field.
func ClientRecordIDContainsFold(v string) predicate.Record {
	return predicate.Record(sql.FieldContainsFold(FieldClientRecordID, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Record {
	return predicate.Record(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Record {
	return predicate.Record(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMusic applies the HasEdge predicate on the "music" edge.
func HasMusic() predicate.Record {
	return predicate.Record(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MusicTable, MusicColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMusicWith applies the HasEdge predicate on the "music" edge with a given conditions (other predicates).
func HasMusicWith(preds ...predicate.Music) predicate.Record {
	return predicate.Record(func(s *sql.Selector) {
		step := newMusicStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStage applies the HasEdge predicate on the "stage" edge.
func HasStage() predicate.Record {
	return predicate.Record(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, StageTable, StageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStageWith applies the HasEdge predicate on the "stage" edge with a given conditions (other predicates).
func HasStageWith(preds ...predicate.Stage) predicate.Record {
	return predicate.Record(func(s *sql.Selector) {
		step := newStageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Record) predicate.Record {
	return predicate.Record(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Record) predicate.Record {
	return predicate.Record(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Record) predicate.Record {
	return predicate.Record(sql.NotPredicates(p))
}
