// Code generated by ent, DO NOT EDIT.

package tlevel

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the tlevel type in the database.
	Label = "tlevel"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRequireExp holds the string denoting the require_exp field in the database.
	FieldRequireExp = "require_exp"
	// Table holds the table name of the tlevel in the database.
	Table = "t_level"
)

// Columns holds all SQL columns for tlevel fields.
var Columns = []string{
	FieldID,
	FieldRequireExp,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the TLevel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRequireExp orders the results by the require_exp field.
func ByRequireExp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequireExp, opts...).ToFunc()
}
