// Code generated by ent, DO NOT EDIT.

package tlevel

import (
	"entgo.io/ent/dialect/sql"
	"github.com/witchs-lounge_backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TLevel {
	return predicate.TLevel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TLevel {
	return predicate.TLevel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TLevel {
	return predicate.TLevel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TLevel {
	return predicate.TLevel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TLevel {
	return predicate.TLevel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TLevel {
	return predicate.TLevel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TLevel {
	return predicate.TLevel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TLevel {
	return predicate.TLevel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TLevel {
	return predicate.TLevel(sql.FieldLTE(FieldID, id))
}

// RequireExp applies equality check predicate on the "require_exp" field. It's identical to RequireExpEQ.
func RequireExp(v int) predicate.TLevel {
	return predicate.TLevel(sql.FieldEQ(FieldRequireExp, v))
}

// RequireExpEQ applies the EQ predicate on the "require_exp" field.
func RequireExpEQ(v int) predicate.TLevel {
	return predicate.TLevel(sql.FieldEQ(FieldRequireExp, v))
}

// RequireExpNEQ applies the NEQ predicate on the "require_exp" field.
func RequireExpNEQ(v int) predicate.TLevel {
	return predicate.TLevel(sql.FieldNEQ(FieldRequireExp, v))
}

// RequireExpIn applies the In predicate on the "require_exp" field.
func RequireExpIn(vs ...int) predicate.TLevel {
	return predicate.TLevel(sql.FieldIn(FieldRequireExp, vs...))
}

// RequireExpNotIn applies the NotIn predicate on the "require_exp" field.
func RequireExpNotIn(vs ...int) predicate.TLevel {
	return predicate.TLevel(sql.FieldNotIn(FieldRequireExp, vs...))
}

// RequireExpGT applies the GT predicate on the "require_exp" field.
func RequireExpGT(v int) predicate.TLevel {
	return predicate.TLevel(sql.FieldGT(FieldRequireExp, v))
}

// RequireExpGTE applies the GTE predicate on the "require_exp" field.
func RequireExpGTE(v int) predicate.TLevel {
	return predicate.TLevel(sql.FieldGTE(FieldRequireExp, v))
}

// RequireExpLT applies the LT predicate on the "require_exp" field.
func RequireExpLT(v int) predicate.TLevel {
	return predicate.TLevel(sql.FieldLT(FieldRequireExp, v))
}

// RequireExpLTE applies the LTE predicate on the "require_exp" field.
func RequireExpLTE(v int) predicate.TLevel {
	return predicate.TLevel(sql.FieldLTE(FieldRequireExp, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TLevel) predicate.TLevel {
	return predicate.TLevel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TLevel) predicate.TLevel {
	return predicate.TLevel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TLevel) predicate.TLevel {
	return predicate.TLevel(sql.NotPredicates(p))
}
