// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/witchs-lounge_backend/ent/consentlog"
	"github.com/witchs-lounge_backend/ent/predicate"
)

// ConsentLogDelete is the builder for deleting a ConsentLog entity.
type ConsentLogDelete struct {
	config
	hooks    []Hook
	mutation *ConsentLogMutation
}

// Where appends a list predicates to the ConsentLogDelete builder.
func (cld *ConsentLogDelete) Where(ps ...predicate.ConsentLog) *ConsentLogDelete {
	cld.mutation.Where(ps...)
	return cld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cld *ConsentLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cld.sqlExec, cld.mutation, cld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cld *ConsentLogDelete) ExecX(ctx context.Context) int {
	n, err := cld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cld *ConsentLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(consentlog.Table, sqlgraph.NewFieldSpec(consentlog.FieldID, field.TypeUUID))
	if ps := cld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cld.mutation.done = true
	return affected, err
}

// ConsentLogDeleteOne is the builder for deleting a single ConsentLog entity.
type ConsentLogDeleteOne struct {
	cld *ConsentLogDelete
}

// Where appends a list predicates to the ConsentLogDelete builder.
func (cldo *ConsentLogDeleteOne) Where(ps ...predicate.ConsentLog) *ConsentLogDeleteOne {
	cldo.cld.mutation.Where(ps...)
	return cldo
}

// Exec executes the deletion query.
func (cldo *ConsentLogDeleteOne) Exec(ctx context.Context) error {
	n, err := cldo.cld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{consentlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cldo *ConsentLogDeleteOne) ExecX(ctx context.Context) {
	if err := cldo.Exec(ctx); err != nil {
		panic(err)
	}
}
