// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/witchs-lounge_backend/ent/consentlog"
)

// ConsentLogCreate is the builder for creating a ConsentLog entity.
type ConsentLogCreate struct {
	config
	mutation *ConsentLogMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (clc *ConsentLogCreate) SetCreatedAt(t time.Time) *ConsentLogCreate {
	clc.mutation.SetCreatedAt(t)
	return clc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (clc *ConsentLogCreate) SetNillableCreatedAt(t *time.Time) *ConsentLogCreate {
	if t != nil {
		clc.SetCreatedAt(*t)
	}
	return clc
}

// SetUpdatedAt sets the "updated_at" field.
func (clc *ConsentLogCreate) SetUpdatedAt(t time.Time) *ConsentLogCreate {
	clc.mutation.SetUpdatedAt(t)
	return clc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (clc *ConsentLogCreate) SetNillableUpdatedAt(t *time.Time) *ConsentLogCreate {
	if t != nil {
		clc.SetUpdatedAt(*t)
	}
	return clc
}

// SetClientConsentID sets the "client_consent_id" field.
func (clc *ConsentLogCreate) SetClientConsentID(u uuid.UUID) *ConsentLogCreate {
	clc.mutation.SetClientConsentID(u)
	return clc
}

// SetClientID sets the "client_id" field.
func (clc *ConsentLogCreate) SetClientID(u uuid.UUID) *ConsentLogCreate {
	clc.mutation.SetClientID(u)
	return clc
}

// SetUserID sets the "user_id" field.
func (clc *ConsentLogCreate) SetUserID(u uuid.UUID) *ConsentLogCreate {
	clc.mutation.SetUserID(u)
	return clc
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (clc *ConsentLogCreate) SetNillableUserID(u *uuid.UUID) *ConsentLogCreate {
	if u != nil {
		clc.SetUserID(*u)
	}
	return clc
}

// SetConsentType sets the "consent_type" field.
func (clc *ConsentLogCreate) SetConsentType(ct consentlog.ConsentType) *ConsentLogCreate {
	clc.mutation.SetConsentType(ct)
	return clc
}

// SetPolicyVersion sets the "policy_version" field.
func (clc *ConsentLogCreate) SetPolicyVersion(s string) *ConsentLogCreate {
	clc.mutation.SetPolicyVersion(s)
	return clc
}

// SetGranted sets the "granted" field.
func (clc *ConsentLogCreate) SetGranted(b bool) *ConsentLogCreate {
	clc.mutation.SetGranted(b)
	return clc
}

// SetNickname sets the "nickname" field.
func (clc *ConsentLogCreate) SetNickname(s string) *ConsentLogCreate {
	clc.mutation.SetNickname(s)
	return clc
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (clc *ConsentLogCreate) SetNillableNickname(s *string) *ConsentLogCreate {
	if s != nil {
		clc.SetNickname(*s)
	}
	return clc
}

// SetConsentedAt sets the "consented_at" field.
func (clc *ConsentLogCreate) SetConsentedAt(t time.Time) *ConsentLogCreate {
	clc.mutation.SetConsentedAt(t)
	return clc
}

// SetClientVersion sets the "client_version" field.
func (clc *ConsentLogCreate) SetClientVersion(s string) *ConsentLogCreate {
	clc.mutation.SetClientVersion(s)
	return clc
}

// SetNillableClientVersion sets the "client_version" field if the given value is not nil.
func (clc *ConsentLogCreate) SetNillableClientVersion(s *string) *ConsentLogCreate {
	if s != nil {
		clc.SetClientVersion(*s)
	}
	return clc
}

// SetPlatform sets the "platform" field.
func (clc *ConsentLogCreate) SetPlatform(s string) *ConsentLogCreate {
	clc.mutation.SetPlatform(s)
	return clc
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (clc *ConsentLogCreate) SetNillablePlatform(s *string) *ConsentLogCreate {
	if s != nil {
		clc.SetPlatform(*s)
	}
	return clc
}

// SetLocale sets the "locale" field.
func (clc *ConsentLogCreate) SetLocale(s string) *ConsentLogCreate {
	clc.mutation.SetLocale(s)
	return clc
}

// SetNillableLocale sets the "locale" field if the given value is not nil.
func (clc *ConsentLogCreate) SetNillableLocale(s *string) *ConsentLogCreate {
	if s != nil {
		clc.SetLocale(*s)
	}
	return clc
}

// SetBuildMode sets the "build_mode" field.
func (clc *ConsentLogCreate) SetBuildMode(s string) *ConsentLogCreate {
	clc.mutation.SetBuildMode(s)
	return clc
}

// SetNillableBuildMode sets the "build_mode" field if the given value is not nil.
func (clc *ConsentLogCreate) SetNillableBuildMode(s *string) *ConsentLogCreate {
	if s != nil {
		clc.SetBuildMode(*s)
	}
	return clc
}

// SetReceivedAt sets the "received_at" field.
func (clc *ConsentLogCreate) SetReceivedAt(t time.Time) *ConsentLogCreate {
	clc.mutation.SetReceivedAt(t)
	return clc
}

// SetNillableReceivedAt sets the "received_at" field if the given value is not nil.
func (clc *ConsentLogCreate) SetNillableReceivedAt(t *time.Time) *ConsentLogCreate {
	if t != nil {
		clc.SetReceivedAt(*t)
	}
	return clc
}

// SetExpiresAt sets the "expires_at" field.
func (clc *ConsentLogCreate) SetExpiresAt(t time.Time) *ConsentLogCreate {
	clc.mutation.SetExpiresAt(t)
	return clc
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (clc *ConsentLogCreate) SetNillableExpiresAt(t *time.Time) *ConsentLogCreate {
	if t != nil {
		clc.SetExpiresAt(*t)
	}
	return clc
}

// SetID sets the "id" field.
func (clc *ConsentLogCreate) SetID(u uuid.UUID) *ConsentLogCreate {
	clc.mutation.SetID(u)
	return clc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (clc *ConsentLogCreate) SetNillableID(u *uuid.UUID) *ConsentLogCreate {
	if u != nil {
		clc.SetID(*u)
	}
	return clc
}

// Mutation returns the ConsentLogMutation object of the builder.
func (clc *ConsentLogCreate) Mutation() *ConsentLogMutation {
	return clc.mutation
}

// Save creates the ConsentLog in the database.
func (clc *ConsentLogCreate) Save(ctx context.Context) (*ConsentLog, error) {
	clc.defaults()
	return withHooks(ctx, clc.sqlSave, clc.mutation, clc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (clc *ConsentLogCreate) SaveX(ctx context.Context) *ConsentLog {
	v, err := clc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (clc *ConsentLogCreate) Exec(ctx context.Context) error {
	_, err := clc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (clc *ConsentLogCreate) ExecX(ctx context.Context) {
	if err := clc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (clc *ConsentLogCreate) defaults() {
	if _, ok := clc.mutation.CreatedAt(); !ok {
		v := consentlog.DefaultCreatedAt()
		clc.mutation.SetCreatedAt(v)
	}
	if _, ok := clc.mutation.UpdatedAt(); !ok {
		v := consentlog.DefaultUpdatedAt()
		clc.mutation.SetUpdatedAt(v)
	}
	if _, ok := clc.mutation.ReceivedAt(); !ok {
		v := consentlog.DefaultReceivedAt()
		clc.mutation.SetReceivedAt(v)
	}
	if _, ok := clc.mutation.ID(); !ok {
		v := consentlog.DefaultID()
		clc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (clc *ConsentLogCreate) check() error {
	if _, ok := clc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ConsentLog.created_at"`)}
	}
	if _, ok := clc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ConsentLog.updated_at"`)}
	}
	if _, ok := clc.mutation.ClientConsentID(); !ok {
		return &ValidationError{Name: "client_consent_id", err: errors.New(`ent: missing required field "ConsentLog.client_consent_id"`)}
	}
	if _, ok := clc.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "ConsentLog.client_id"`)}
	}
	if _, ok := clc.mutation.ConsentType(); !ok {
		return &ValidationError{Name: "consent_type", err: errors.New(`ent: missing required field "ConsentLog.consent_type"`)}
	}
	if v, ok := clc.mutation.ConsentType(); ok {
		if err := consentlog.ConsentTypeValidator(v); err != nil {
			return &ValidationError{Name: "consent_type", err: fmt.Errorf(`ent: validator failed for field "ConsentLog.consent_type": %w`, err)}
		}
	}
	if _, ok := clc.mutation.PolicyVersion(); !ok {
		return &ValidationError{Name: "policy_version", err: errors.New(`ent: missing required field "ConsentLog.policy_version"`)}
	}
	if v, ok := clc.mutation.PolicyVersion(); ok {
		if err := consentlog.PolicyVersionValidator(v); err != nil {
			return &ValidationError{Name: "policy_version", err: fmt.Errorf(`ent: validator failed for field "ConsentLog.policy_version": %w`, err)}
		}
	}
	if _, ok := clc.mutation.Granted(); !ok {
		return &ValidationError{Name: "granted", err: errors.New(`ent: missing required field "ConsentLog.granted"`)}
	}
	if v, ok := clc.mutation.Nickname(); ok {
		if err := consentlog.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "ConsentLog.nickname": %w`, err)}
		}
	}
	if _, ok := clc.mutation.ConsentedAt(); !ok {
		return &ValidationError{Name: "consented_at", err: errors.New(`ent: missing required field "ConsentLog.consented_at"`)}
	}
	if v, ok := clc.mutation.ClientVersion(); ok {
		if err := consentlog.ClientVersionValidator(v); err != nil {
			return &ValidationError{Name: "client_version", err: fmt.Errorf(`ent: validator failed for field "ConsentLog.client_version": %w`, err)}
		}
	}
	if v, ok := clc.mutation.Platform(); ok {
		if err := consentlog.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ConsentLog.platform": %w`, err)}
		}
	}
	if v, ok := clc.mutation.Locale(); ok {
		if err := consentlog.LocaleValidator(v); err != nil {
			return &ValidationError{Name: "locale", err: fmt.Errorf(`ent: validator failed for field "ConsentLog.locale": %w`, err)}
		}
	}
	if v, ok := clc.mutation.BuildMode(); ok {
		if err := consentlog.BuildModeValidator(v); err != nil {
			return &ValidationError{Name: "build_mode", err: fmt.Errorf(`ent: validator failed for field "ConsentLog.build_mode": %w`, err)}
		}
	}
	if _, ok := clc.mutation.ReceivedAt(); !ok {
		return &ValidationError{Name: "received_at", err: errors.New(`ent: missing required field "ConsentLog.received_at"`)}
	}
	return nil
}

func (clc *ConsentLogCreate) sqlSave(ctx context.Context) (*ConsentLog, error) {
	if err := clc.check(); err != nil {
		return nil, err
	}
	_node, _spec := clc.createSpec()
	if err := sqlgraph.CreateNode(ctx, clc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	clc.mutation.id = &_node.ID
	clc.mutation.done = true
	return _node, nil
}

func (clc *ConsentLogCreate) createSpec() (*ConsentLog, *sqlgraph.CreateSpec) {
	var (
		_node = &ConsentLog{config: clc.config}
		_spec = sqlgraph.NewCreateSpec(consentlog.Table, sqlgraph.NewFieldSpec(consentlog.FieldID, field.TypeUUID))
	)
	if id, ok := clc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := clc.mutation.CreatedAt(); ok {
		_spec.SetField(consentlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := clc.mutation.UpdatedAt(); ok {
		_spec.SetField(consentlog.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := clc.mutation.ClientConsentID(); ok {
		_spec.SetField(consentlog.FieldClientConsentID, field.TypeUUID, value)
		_node.ClientConsentID = value
	}
	if value, ok := clc.mutation.ClientID(); ok {
		_spec.SetField(consentlog.FieldClientID, field.TypeUUID, value)
		_node.ClientID = value
	}
	if value, ok := clc.mutation.UserID(); ok {
		_spec.SetField(consentlog.FieldUserID, field.TypeUUID, value)
		_node.UserID = &value
	}
	if value, ok := clc.mutation.ConsentType(); ok {
		_spec.SetField(consentlog.FieldConsentType, field.TypeEnum, value)
		_node.ConsentType = value
	}
	if value, ok := clc.mutation.PolicyVersion(); ok {
		_spec.SetField(consentlog.FieldPolicyVersion, field.TypeString, value)
		_node.PolicyVersion = value
	}
	if value, ok := clc.mutation.Granted(); ok {
		_spec.SetField(consentlog.FieldGranted, field.TypeBool, value)
		_node.Granted = value
	}
	if value, ok := clc.mutation.Nickname(); ok {
		_spec.SetField(consentlog.FieldNickname, field.TypeString, value)
		_node.Nickname = value
	}
	if value, ok := clc.mutation.ConsentedAt(); ok {
		_spec.SetField(consentlog.FieldConsentedAt, field.TypeTime, value)
		_node.ConsentedAt = value
	}
	if value, ok := clc.mutation.ClientVersion(); ok {
		_spec.SetField(consentlog.FieldClientVersion, field.TypeString, value)
		_node.ClientVersion = value
	}
	if value, ok := clc.mutation.Platform(); ok {
		_spec.SetField(consentlog.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := clc.mutation.Locale(); ok {
		_spec.SetField(consentlog.FieldLocale, field.TypeString, value)
		_node.Locale = value
	}
	if value, ok := clc.mutation.BuildMode(); ok {
		_spec.SetField(consentlog.FieldBuildMode, field.TypeString, value)
		_node.BuildMode = value
	}
	if value, ok := clc.mutation.ReceivedAt(); ok {
		_spec.SetField(consentlog.FieldReceivedAt, field.TypeTime, value)
		_node.ReceivedAt = value
	}
	if value, ok := clc.mutation.ExpiresAt(); ok {
		_spec.SetField(consentlog.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	return _node, _spec
}

// ConsentLogCreateBulk is the builder for creating many ConsentLog entities in bulk.
type ConsentLogCreateBulk struct {
	config
	err      error
	builders []*ConsentLogCreate
}

// Save creates the ConsentLog entities in the database.
func (clcb *ConsentLogCreateBulk) Save(ctx context.Context) ([]*ConsentLog, error) {
	if clcb.err != nil {
		return nil, clcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(clcb.builders))
	nodes := make([]*ConsentLog, len(clcb.builders))
	mutators := make([]Mutator, len(clcb.builders))
	for i := range clcb.builders {
		func(i int, root context.Context) {
			builder := clcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConsentLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, clcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, clcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, clcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (clcb *ConsentLogCreateBulk) SaveX(ctx context.Context) []*ConsentLog {
	v, err := clcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (clcb *ConsentLogCreateBulk) Exec(ctx context.Context) error {
	_, err := clcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (clcb *ConsentLogCreateBulk) ExecX(ctx context.Context) {
	if err := clcb.Exec(ctx); err != nil {
		panic(err)
	}
}
