// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/witchs-lounge_backend/ent/consentlog"
	"github.com/witchs-lounge_backend/ent/predicate"
)

// ConsentLogUpdate is the builder for updating ConsentLog entities.
type ConsentLogUpdate struct {
	config
	hooks    []Hook
	mutation *ConsentLogMutation
}

// Where appends a list predicates to the ConsentLogUpdate builder.
func (clu *ConsentLogUpdate) Where(ps ...predicate.ConsentLog) *ConsentLogUpdate {
	clu.mutation.Where(ps...)
	return clu
}

// SetUpdatedAt sets the "updated_at" field.
func (clu *ConsentLogUpdate) SetUpdatedAt(t time.Time) *ConsentLogUpdate {
	clu.mutation.SetUpdatedAt(t)
	return clu
}

// SetClientConsentID sets the "client_consent_id" field.
func (clu *ConsentLogUpdate) SetClientConsentID(u uuid.UUID) *ConsentLogUpdate {
	clu.mutation.SetClientConsentID(u)
	return clu
}

// SetNillableClientConsentID sets the "client_consent_id" field if the given value is not nil.
func (clu *ConsentLogUpdate) SetNillableClientConsentID(u *uuid.UUID) *ConsentLogUpdate {
	if u != nil {
		clu.SetClientConsentID(*u)
	}
	return clu
}

// SetClientID sets the "client_id" field.
func (clu *ConsentLogUpdate) SetClientID(u uuid.UUID) *ConsentLogUpdate {
	clu.mutation.SetClientID(u)
	return clu
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (clu *ConsentLogUpdate) SetNillableClientID(u *uuid.UUID) *ConsentLogUpdate {
	if u != nil {
		clu.SetClientID(*u)
	}
	return clu
}

// SetUserID sets the "user_id" field.
func (clu *ConsentLogUpdate) SetUserID(u uuid.UUID) *ConsentLogUpdate {
	clu.mutation.SetUserID(u)
	return clu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (clu *ConsentLogUpdate) SetNillableUserID(u *uuid.UUID) *ConsentLogUpdate {
	if u != nil {
		clu.SetUserID(*u)
	}
	return clu
}

// ClearUserID clears the value of the "user_id" field.
func (clu *ConsentLogUpdate) ClearUserID() *ConsentLogUpdate {
	clu.mutation.ClearUserID()
	return clu
}

// SetConsentType sets the "consent_type" field.
func (clu *ConsentLogUpdate) SetConsentType(ct consentlog.ConsentType) *ConsentLogUpdate {
	clu.mutation.SetConsentType(ct)
	return clu
}

// SetNillableConsentType sets the "consent_type" field if the given value is not nil.
func (clu *ConsentLogUpdate) SetNillableConsentType(ct *consentlog.ConsentType) *ConsentLogUpdate {
	if ct != nil {
		clu.SetConsentType(*ct)
	}
	return clu
}

// SetPolicyVersion sets the "policy_version" field.
func (clu *ConsentLogUpdate) SetPolicyVersion(s string) *ConsentLogUpdate {
	clu.mutation.SetPolicyVersion(s)
	return clu
}

// SetNillablePolicyVersion sets the "policy_version" field if the given value is not nil.
func (clu *ConsentLogUpdate) SetNillablePolicyVersion(s *string) *ConsentLogUpdate {
	if s != nil {
		clu.SetPolicyVersion(*s)
	}
	return clu
}

// SetGranted sets the "granted" field.
func (clu *ConsentLogUpdate) SetGranted(b bool) *ConsentLogUpdate {
	clu.mutation.SetGranted(b)
	return clu
}

// SetNillableGranted sets the "granted" field if the given value is not nil.
func (clu *ConsentLogUpdate) SetNillableGranted(b *bool) *ConsentLogUpdate {
	if b != nil {
		clu.SetGranted(*b)
	}
	return clu
}

// SetNickname sets the "nickname" field.
func (clu *ConsentLogUpdate) SetNickname(s string) *ConsentLogUpdate {
	clu.mutation.SetNickname(s)
	return clu
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (clu *ConsentLogUpdate) SetNillableNickname(s *string) *ConsentLogUpdate {
	if s != nil {
		clu.SetNickname(*s)
	}
	return clu
}

// ClearNickname clears the value of the "nickname" field.
func (clu *ConsentLogUpdate) ClearNickname() *ConsentLogUpdate {
	clu.mutation.ClearNickname()
	return clu
}

// SetConsentedAt sets the "consented_at" field.
func (clu *ConsentLogUpdate) SetConsentedAt(t time.Time) *ConsentLogUpdate {
	clu.mutation.SetConsentedAt(t)
	return clu
}

// SetNillableConsentedAt sets the "consented_at" field if the given value is not nil.
func (clu *ConsentLogUpdate) SetNillableConsentedAt(t *time.Time) *ConsentLogUpdate {
	if t != nil {
		clu.SetConsentedAt(*t)
	}
	return clu
}

// SetClientVersion sets the "client_version" field.
func (clu *ConsentLogUpdate) SetClientVersion(s string) *ConsentLogUpdate {
	clu.mutation.SetClientVersion(s)
	return clu
}

// SetNillableClientVersion sets the "client_version" field if the given value is not nil.
func (clu *ConsentLogUpdate) SetNillableClientVersion(s *string) *ConsentLogUpdate {
	if s != nil {
		clu.SetClientVersion(*s)
	}
	return clu
}

// ClearClientVersion clears the value of the "client_version" field.
func (clu *ConsentLogUpdate) ClearClientVersion() *ConsentLogUpdate {
	clu.mutation.ClearClientVersion()
	return clu
}

// SetPlatform sets the "platform" field.
func (clu *ConsentLogUpdate) SetPlatform(s string) *ConsentLogUpdate {
	clu.mutation.SetPlatform(s)
	return clu
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (clu *ConsentLogUpdate) SetNillablePlatform(s *string) *ConsentLogUpdate {
	if s != nil {
		clu.SetPlatform(*s)
	}
	return clu
}

// ClearPlatform clears the value of the "platform" field.
func (clu *ConsentLogUpdate) ClearPlatform() *ConsentLogUpdate {
	clu.mutation.ClearPlatform()
	return clu
}

// SetLocale sets the "locale" field.
func (clu *ConsentLogUpdate) SetLocale(s string) *ConsentLogUpdate {
	clu.mutation.SetLocale(s)
	return clu
}

// SetNillableLocale sets the "locale" field if the given value is not nil.
func (clu *ConsentLogUpdate) SetNillableLocale(s *string) *ConsentLogUpdate {
	if s != nil {
		clu.SetLocale(*s)
	}
	return clu
}

// ClearLocale clears the value of the "locale" field.
func (clu *ConsentLogUpdate) ClearLocale() *ConsentLogUpdate {
	clu.mutation.ClearLocale()
	return clu
}

// SetBuildMode sets the "build_mode" field.
func (clu *ConsentLogUpdate) SetBuildMode(s string) *ConsentLogUpdate {
	clu.mutation.SetBuildMode(s)
	return clu
}

// SetNillableBuildMode sets the "build_mode" field if the given value is not nil.
func (clu *ConsentLogUpdate) SetNillableBuildMode(s *string) *ConsentLogUpdate {
	if s != nil {
		clu.SetBuildMode(*s)
	}
	return clu
}

// ClearBuildMode clears the value of the "build_mode" field.
func (clu *ConsentLogUpdate) ClearBuildMode() *ConsentLogUpdate {
	clu.mutation.ClearBuildMode()
	return clu
}

// SetReceivedAt sets the "received_at" field.
func (clu *ConsentLogUpdate) SetReceivedAt(t time.Time) *ConsentLogUpdate {
	clu.mutation.SetReceivedAt(t)
	return clu
}

// SetNillableReceivedAt sets the "received_at" field if the given value is not nil.
func (clu *ConsentLogUpdate) SetNillableReceivedAt(t *time.Time) *ConsentLogUpdate {
	if t != nil {
		clu.SetReceivedAt(*t)
	}
	return clu
}

// SetExpiresAt sets the "expires_at" field.
func (clu *ConsentLogUpdate) SetExpiresAt(t time.Time) *ConsentLogUpdate {
	clu.mutation.SetExpiresAt(t)
	return clu
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (clu *ConsentLogUpdate) SetNillableExpiresAt(t *time.Time) *ConsentLogUpdate {
	if t != nil {
		clu.SetExpiresAt(*t)
	}
	return clu
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (clu *ConsentLogUpdate) ClearExpiresAt() *ConsentLogUpdate {
	clu.mutation.ClearExpiresAt()
	return clu
}

// Mutation returns the ConsentLogMutation object of the builder.
func (clu *ConsentLogUpdate) Mutation() *ConsentLogMutation {
	return clu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (clu *ConsentLogUpdate) Save(ctx context.Context) (int, error) {
	clu.defaults()
	return withHooks(ctx, clu.sqlSave, clu.mutation, clu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (clu *ConsentLogUpdate) SaveX(ctx context.Context) int {
	affected, err := clu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (clu *ConsentLogUpdate) Exec(ctx context.Context) error {
	_, err := clu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (clu *ConsentLogUpdate) ExecX(ctx context.Context) {
	if err := clu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (clu *ConsentLogUpdate) defaults() {
	if _, ok := clu.mutation.UpdatedAt(); !ok {
		v := consentlog.UpdateDefaultUpdatedAt()
		clu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (clu *ConsentLogUpdate) check() error {
	if v, ok := clu.mutation.ConsentType(); ok {
		if err := consentlog.ConsentTypeValidator(v); err != nil {
			return &ValidationError{Name: "consent_type", err: fmt.Errorf(`ent: validator failed for field "ConsentLog.consent_type": %w`, err)}
		}
	}
	if v, ok := clu.mutation.PolicyVersion(); ok {
		if err := consentlog.PolicyVersionValidator(v); err != nil {
			return &ValidationError{Name: "policy_version", err: fmt.Errorf(`ent: validator failed for field "ConsentLog.policy_version": %w`, err)}
		}
	}
	if v, ok := clu.mutation.Nickname(); ok {
		if err := consentlog.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "ConsentLog.nickname": %w`, err)}
		}
	}
	if v, ok := clu.mutation.ClientVersion(); ok {
		if err := consentlog.ClientVersionValidator(v); err != nil {
			return &ValidationError{Name: "client_version", err: fmt.Errorf(`ent: validator failed for field "ConsentLog.client_version": %w`, err)}
		}
	}
	if v, ok := clu.mutation.Platform(); ok {
		if err := consentlog.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ConsentLog.platform": %w`, err)}
		}
	}
	if v, ok := clu.mutation.Locale(); ok {
		if err := consentlog.LocaleValidator(v); err != nil {
			return &ValidationError{Name: "locale", err: fmt.Errorf(`ent: validator failed for field "ConsentLog.locale": %w`, err)}
		}
	}
	if v, ok := clu.mutation.BuildMode(); ok {
		if err := consentlog.BuildModeValidator(v); err != nil {
			return &ValidationError{Name: "build_mode", err: fmt.Errorf(`ent: validator failed for field "ConsentLog.build_mode": %w`, err)}
		}
	}
	return nil
}

func (clu *ConsentLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := clu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(consentlog.Table, consentlog.Columns, sqlgraph.NewFieldSpec(consentlog.FieldID, field.TypeUUID))
	if ps := clu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := clu.mutation.UpdatedAt(); ok {
		_spec.SetField(consentlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := clu.mutation.ClientConsentID(); ok {
		_spec.SetField(consentlog.FieldClientConsentID, field.TypeUUID, value)
	}
	if value, ok := clu.mutation.ClientID(); ok {
		_spec.SetField(consentlog.FieldClientID, field.TypeUUID, value)
	}
	if value, ok := clu.mutation.UserID(); ok {
		_spec.SetField(consentlog.FieldUserID, field.TypeUUID, value)
	}
	if clu.mutation.UserIDCleared() {
		_spec.ClearField(consentlog.FieldUserID, field.TypeUUID)
	}
	if value, ok := clu.mutation.ConsentType(); ok {
		_spec.SetField(consentlog.FieldConsentType, field.TypeEnum, value)
	}
	if value, ok := clu.mutation.PolicyVersion(); ok {
		_spec.SetField(consentlog.FieldPolicyVersion, field.TypeString, value)
	}
	if value, ok := clu.mutation.Granted(); ok {
		_spec.SetField(consentlog.FieldGranted, field.TypeBool, value)
	}
	if value, ok := clu.mutation.Nickname(); ok {
		_spec.SetField(consentlog.FieldNickname, field.TypeString, value)
	}
	if clu.mutation.NicknameCleared() {
		_spec.ClearField(consentlog.FieldNickname, field.TypeString)
	}
	if value, ok := clu.mutation.ConsentedAt(); ok {
		_spec.SetField(consentlog.FieldConsentedAt, field.TypeTime, value)
	}
	if value, ok := clu.mutation.ClientVersion(); ok {
		_spec.SetField(consentlog.FieldClientVersion, field.TypeString, value)
	}
	if clu.mutation.ClientVersionCleared() {
		_spec.ClearField(consentlog.FieldClientVersion, field.TypeString)
	}
	if value, ok := clu.mutation.Platform(); ok {
		_spec.SetField(consentlog.FieldPlatform, field.TypeString, value)
	}
	if clu.mutation.PlatformCleared() {
		_spec.ClearField(consentlog.FieldPlatform, field.TypeString)
	}
	if value, ok := clu.mutation.Locale(); ok {
		_spec.SetField(consentlog.FieldLocale, field.TypeString, value)
	}
	if clu.mutation.LocaleCleared() {
		_spec.ClearField(consentlog.FieldLocale, field.TypeString)
	}
	if value, ok := clu.mutation.BuildMode(); ok {
		_spec.SetField(consentlog.FieldBuildMode, field.TypeString, value)
	}
	if clu.mutation.BuildModeCleared() {
		_spec.ClearField(consentlog.FieldBuildMode, field.TypeString)
	}
	if value, ok := clu.mutation.ReceivedAt(); ok {
		_spec.SetField(consentlog.FieldReceivedAt, field.TypeTime, value)
	}
	if value, ok := clu.mutation.ExpiresAt(); ok {
		_spec.SetField(consentlog.FieldExpiresAt, field.TypeTime, value)
	}
	if clu.mutation.ExpiresAtCleared() {
		_spec.ClearField(consentlog.FieldExpiresAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, clu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{consentlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	clu.mutation.done = true
	return n, nil
}

// ConsentLogUpdateOne is the builder for updating a single ConsentLog entity.
type ConsentLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConsentLogMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (cluo *ConsentLogUpdateOne) SetUpdatedAt(t time.Time) *ConsentLogUpdateOne {
	cluo.mutation.SetUpdatedAt(t)
	return cluo
}

// SetClientConsentID sets the "client_consent_id" field.
func (cluo *ConsentLogUpdateOne) SetClientConsentID(u uuid.UUID) *ConsentLogUpdateOne {
	cluo.mutation.SetClientConsentID(u)
	return cluo
}

// SetNillableClientConsentID sets the "client_consent_id" field if the given value is not nil.
func (cluo *ConsentLogUpdateOne) SetNillableClientConsentID(u *uuid.UUID) *ConsentLogUpdateOne {
	if u != nil {
		cluo.SetClientConsentID(*u)
	}
	return cluo
}

// SetClientID sets the "client_id" field.
func (cluo *ConsentLogUpdateOne) SetClientID(u uuid.UUID) *ConsentLogUpdateOne {
	cluo.mutation.SetClientID(u)
	return cluo
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (cluo *ConsentLogUpdateOne) SetNillableClientID(u *uuid.UUID) *ConsentLogUpdateOne {
	if u != nil {
		cluo.SetClientID(*u)
	}
	return cluo
}

// SetUserID sets the "user_id" field.
func (cluo *ConsentLogUpdateOne) SetUserID(u uuid.UUID) *ConsentLogUpdateOne {
	cluo.mutation.SetUserID(u)
	return cluo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (cluo *ConsentLogUpdateOne) SetNillableUserID(u *uuid.UUID) *ConsentLogUpdateOne {
	if u != nil {
		cluo.SetUserID(*u)
	}
	return cluo
}

// ClearUserID clears the value of the "user_id" field.
func (cluo *ConsentLogUpdateOne) ClearUserID() *ConsentLogUpdateOne {
	cluo.mutation.ClearUserID()
	return cluo
}

// SetConsentType sets the "consent_type" field.
func (cluo *ConsentLogUpdateOne) SetConsentType(ct consentlog.ConsentType) *ConsentLogUpdateOne {
	cluo.mutation.SetConsentType(ct)
	return cluo
}

// SetNillableConsentType sets the "consent_type" field if the given value is not nil.
func (cluo *ConsentLogUpdateOne) SetNillableConsentType(ct *consentlog.ConsentType) *ConsentLogUpdateOne {
	if ct != nil {
		cluo.SetConsentType(*ct)
	}
	return cluo
}

// SetPolicyVersion sets the "policy_version" field.
func (cluo *ConsentLogUpdateOne) SetPolicyVersion(s string) *ConsentLogUpdateOne {
	cluo.mutation.SetPolicyVersion(s)
	return cluo
}

// SetNillablePolicyVersion sets the "policy_version" field if the given value is not nil.
func (cluo *ConsentLogUpdateOne) SetNillablePolicyVersion(s *string) *ConsentLogUpdateOne {
	if s != nil {
		cluo.SetPolicyVersion(*s)
	}
	return cluo
}

// SetGranted sets the "granted" field.
func (cluo *ConsentLogUpdateOne) SetGranted(b bool) *ConsentLogUpdateOne {
	cluo.mutation.SetGranted(b)
	return cluo
}

// SetNillableGranted sets the "granted" field if the given value is not nil.
func (cluo *ConsentLogUpdateOne) SetNillableGranted(b *bool) *ConsentLogUpdateOne {
	if b != nil {
		cluo.SetGranted(*b)
	}
	return cluo
}

// SetNickname sets the "nickname" field.
func (cluo *ConsentLogUpdateOne) SetNickname(s string) *ConsentLogUpdateOne {
	cluo.mutation.SetNickname(s)
	return cluo
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (cluo *ConsentLogUpdateOne) SetNillableNickname(s *string) *ConsentLogUpdateOne {
	if s != nil {
		cluo.SetNickname(*s)
	}
	return cluo
}

// ClearNickname clears the value of the "nickname" field.
func (cluo *ConsentLogUpdateOne) ClearNickname() *ConsentLogUpdateOne {
	cluo.mutation.ClearNickname()
	return cluo
}

// SetConsentedAt sets the "consented_at" field.
func (cluo *ConsentLogUpdateOne) SetConsentedAt(t time.Time) *ConsentLogUpdateOne {
	cluo.mutation.SetConsentedAt(t)
	return cluo
}

// SetNillableConsentedAt sets the "consented_at" field if the given value is not nil.
func (cluo *ConsentLogUpdateOne) SetNillableConsentedAt(t *time.Time) *ConsentLogUpdateOne {
	if t != nil {
		cluo.SetConsentedAt(*t)
	}
	return cluo
}

// SetClientVersion sets the "client_version" field.
func (cluo *ConsentLogUpdateOne) SetClientVersion(s string) *ConsentLogUpdateOne {
	cluo.mutation.SetClientVersion(s)
	return cluo
}

// SetNillableClientVersion sets the "client_version" field if the given value is not nil.
func (cluo *ConsentLogUpdateOne) SetNillableClientVersion(s *string) *ConsentLogUpdateOne {
	if s != nil {
		cluo.SetClientVersion(*s)
	}
	return cluo
}

// ClearClientVersion clears the value of the "client_version" field.
func (cluo *ConsentLogUpdateOne) ClearClientVersion() *ConsentLogUpdateOne {
	cluo.mutation.ClearClientVersion()
	return cluo
}

// SetPlatform sets the "platform" field.
func (cluo *ConsentLogUpdateOne) SetPlatform(s string) *ConsentLogUpdateOne {
	cluo.mutation.SetPlatform(s)
	return cluo
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (cluo *ConsentLogUpdateOne) SetNillablePlatform(s *string) *ConsentLogUpdateOne {
	if s != nil {
		cluo.SetPlatform(*s)
	}
	return cluo
}

// ClearPlatform clears the value of the "platform" field.
func (cluo *ConsentLogUpdateOne) ClearPlatform() *ConsentLogUpdateOne {
	cluo.mutation.ClearPlatform()
	return cluo
}

// SetLocale sets the "locale" field.
func (cluo *ConsentLogUpdateOne) SetLocale(s string) *ConsentLogUpdateOne {
	cluo.mutation.SetLocale(s)
	return cluo
}

// SetNillableLocale sets the "locale" field if the given value is not nil.
func (cluo *ConsentLogUpdateOne) SetNillableLocale(s *string) *ConsentLogUpdateOne {
	if s != nil {
		cluo.SetLocale(*s)
	}
	return cluo
}

// ClearLocale clears the value of the "locale" field.
func (cluo *ConsentLogUpdateOne) ClearLocale() *ConsentLogUpdateOne {
	cluo.mutation.ClearLocale()
	return cluo
}

// SetBuildMode sets the "build_mode" field.
func (cluo *ConsentLogUpdateOne) SetBuildMode(s string) *ConsentLogUpdateOne {
	cluo.mutation.SetBuildMode(s)
	return cluo
}

// SetNillableBuildMode sets the "build_mode" field if the given value is not nil.
func (cluo *ConsentLogUpdateOne) SetNillableBuildMode(s *string) *ConsentLogUpdateOne {
	if s != nil {
		cluo.SetBuildMode(*s)
	}
	return cluo
}

// ClearBuildMode clears the value of the "build_mode" field.
func (cluo *ConsentLogUpdateOne) ClearBuildMode() *ConsentLogUpdateOne {
	cluo.mutation.ClearBuildMode()
	return cluo
}

// SetReceivedAt sets the "received_at" field.
func (cluo *ConsentLogUpdateOne) SetReceivedAt(t time.Time) *ConsentLogUpdateOne {
	cluo.mutation.SetReceivedAt(t)
	return cluo
}

// SetNillableReceivedAt sets the "received_at" field if the given value is not nil.
func (cluo *ConsentLogUpdateOne) SetNillableReceivedAt(t *time.Time) *ConsentLogUpdateOne {
	if t != nil {
		cluo.SetReceivedAt(*t)
	}
	return cluo
}

// SetExpiresAt sets the "expires_at" field.
func (cluo *ConsentLogUpdateOne) SetExpiresAt(t time.Time) *ConsentLogUpdateOne {
	cluo.mutation.SetExpiresAt(t)
	return cluo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (cluo *ConsentLogUpdateOne) SetNillableExpiresAt(t *time.Time) *ConsentLogUpdateOne {
	if t != nil {
		cluo.SetExpiresAt(*t)
	}
	return cluo
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (cluo *ConsentLogUpdateOne) ClearExpiresAt() *ConsentLogUpdateOne {
	cluo.mutation.ClearExpiresAt()
	return cluo
}

// Mutation returns the ConsentLogMutation object of the builder.
func (cluo *ConsentLogUpdateOne) Mutation() *ConsentLogMutation {
	return cluo.mutation
}

// Where appends a list predicates to the ConsentLogUpdate builder.
func (cluo *ConsentLogUpdateOne) Where(ps ...predicate.ConsentLog) *ConsentLogUpdateOne {
	cluo.mutation.Where(ps...)
	return cluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cluo *ConsentLogUpdateOne) Select(field string, fields ...string) *ConsentLogUpdateOne {
	cluo.fields = append([]string{field}, fields...)
	return cluo
}

// Save executes the query and returns the updated ConsentLog entity.
func (cluo *ConsentLogUpdateOne) Save(ctx context.Context) (*ConsentLog, error) {
	cluo.defaults()
	return withHooks(ctx, cluo.sqlSave, cluo.mutation, cluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cluo *ConsentLogUpdateOne) SaveX(ctx context.Context) *ConsentLog {
	node, err := cluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cluo *ConsentLogUpdateOne) Exec(ctx context.Context) error {
	_, err := cluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cluo *ConsentLogUpdateOne) ExecX(ctx context.Context) {
	if err := cluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cluo *ConsentLogUpdateOne) defaults() {
	if _, ok := cluo.mutation.UpdatedAt(); !ok {
		v := consentlog.UpdateDefaultUpdatedAt()
		cluo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cluo *ConsentLogUpdateOne) check() error {
	if v, ok := cluo.mutation.ConsentType(); ok {
		if err := consentlog.ConsentTypeValidator(v); err != nil {
			return &ValidationError{Name: "consent_type", err: fmt.Errorf(`ent: validator failed for field "ConsentLog.consent_type": %w`, err)}
		}
	}
	if v, ok := cluo.mutation.PolicyVersion(); ok {
		if err := consentlog.PolicyVersionValidator(v); err != nil {
			return &ValidationError{Name: "policy_version", err: fmt.Errorf(`ent: validator failed for field "ConsentLog.policy_version": %w`, err)}
		}
	}
	if v, ok := cluo.mutation.Nickname(); ok {
		if err := consentlog.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "ConsentLog.nickname": %w`, err)}
		}
	}
	if v, ok := cluo.mutation.ClientVersion(); ok {
		if err := consentlog.ClientVersionValidator(v); err != nil {
			return &ValidationError{Name: "client_version", err: fmt.Errorf(`ent: validator failed for field "ConsentLog.client_version": %w`, err)}
		}
	}
	if v, ok := cluo.mutation.Platform(); ok {
		if err := consentlog.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ConsentLog.platform": %w`, err)}
		}
	}
	if v, ok := cluo.mutation.Locale(); ok {
		if err := consentlog.LocaleValidator(v); err != nil {
			return &ValidationError{Name: "locale", err: fmt.Errorf(`ent: validator failed for field "ConsentLog.locale": %w`, err)}
		}
	}
	if v, ok := cluo.mutation.BuildMode(); ok {
		if err := consentlog.BuildModeValidator(v); err != nil {
			return &ValidationError{Name: "build_mode", err: fmt.Errorf(`ent: validator failed for field "ConsentLog.build_mode": %w`, err)}
		}
	}
	return nil
}

func (cluo *ConsentLogUpdateOne) sqlSave(ctx context.Context) (_node *ConsentLog, err error) {
	if err := cluo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(consentlog.Table, consentlog.Columns, sqlgraph.NewFieldSpec(consentlog.FieldID, field.TypeUUID))
	id, ok := cluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ConsentLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, consentlog.FieldID)
		for _, f := range fields {
			if !consentlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != consentlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cluo.mutation.UpdatedAt(); ok {
		_spec.SetField(consentlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := cluo.mutation.ClientConsentID(); ok {
		_spec.SetField(consentlog.FieldClientConsentID, field.TypeUUID, value)
	}
	if value, ok := cluo.mutation.ClientID(); ok {
		_spec.SetField(consentlog.FieldClientID, field.TypeUUID, value)
	}
	if value, ok := cluo.mutation.UserID(); ok {
		_spec.SetField(consentlog.FieldUserID, field.TypeUUID, value)
	}
	if cluo.mutation.UserIDCleared() {
		_spec.ClearField(consentlog.FieldUserID, field.TypeUUID)
	}
	if value, ok := cluo.mutation.ConsentType(); ok {
		_spec.SetField(consentlog.FieldConsentType, field.TypeEnum, value)
	}
	if value, ok := cluo.mutation.PolicyVersion(); ok {
		_spec.SetField(consentlog.FieldPolicyVersion, field.TypeString, value)
	}
	if value, ok := cluo.mutation.Granted(); ok {
		_spec.SetField(consentlog.FieldGranted, field.TypeBool, value)
	}
	if value, ok := cluo.mutation.Nickname(); ok {
		_spec.SetField(consentlog.FieldNickname, field.TypeString, value)
	}
	if cluo.mutation.NicknameCleared() {
		_spec.ClearField(consentlog.FieldNickname, field.TypeString)
	}
	if value, ok := cluo.mutation.ConsentedAt(); ok {
		_spec.SetField(consentlog.FieldConsentedAt, field.TypeTime, value)
	}
	if value, ok := cluo.mutation.ClientVersion(); ok {
		_spec.SetField(consentlog.FieldClientVersion, field.TypeString, value)
	}
	if cluo.mutation.ClientVersionCleared() {
		_spec.ClearField(consentlog.FieldClientVersion, field.TypeString)
	}
	if value, ok := cluo.mutation.Platform(); ok {
		_spec.SetField(consentlog.FieldPlatform, field.TypeString, value)
	}
	if cluo.mutation.PlatformCleared() {
		_spec.ClearField(consentlog.FieldPlatform, field.TypeString)
	}
	if value, ok := cluo.mutation.Locale(); ok {
		_spec.SetField(consentlog.FieldLocale, field.TypeString, value)
	}
	if cluo.mutation.LocaleCleared() {
		_spec.ClearField(consentlog.FieldLocale, field.TypeString)
	}
	if value, ok := cluo.mutation.BuildMode(); ok {
		_spec.SetField(consentlog.FieldBuildMode, field.TypeString, value)
	}
	if cluo.mutation.BuildModeCleared() {
		_spec.ClearField(consentlog.FieldBuildMode, field.TypeString)
	}
	if value, ok := cluo.mutation.ReceivedAt(); ok {
		_spec.SetField(consentlog.FieldReceivedAt, field.TypeTime, value)
	}
	if value, ok := cluo.mutation.ExpiresAt(); ok {
		_spec.SetField(consentlog.FieldExpiresAt, field.TypeTime, value)
	}
	if cluo.mutation.ExpiresAtCleared() {
		_spec.ClearField(consentlog.FieldExpiresAt, field.TypeTime)
	}
	_node = &ConsentLog{config: cluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{consentlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cluo.mutation.done = true
	return _node, nil
}
