// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/witchs-lounge_backend/ent/consentlog"
	"github.com/witchs-lounge_backend/ent/predicate"
)

// ConsentLogQuery is the builder for querying ConsentLog entities.
type ConsentLogQuery struct {
	config
	ctx        *QueryContext
	order      []consentlog.OrderOption
	inters     []Interceptor
	predicates []predicate.ConsentLog
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ConsentLogQuery builder.
func (clq *ConsentLogQuery) Where(ps ...predicate.ConsentLog) *ConsentLogQuery {
	clq.predicates = append(clq.predicates, ps...)
	return clq
}

// Limit the number of records to be returned by this query.
func (clq *ConsentLogQuery) Limit(limit int) *ConsentLogQuery {
	clq.ctx.Limit = &limit
	return clq
}

// Offset to start from.
func (clq *ConsentLogQuery) Offset(offset int) *ConsentLogQuery {
	clq.ctx.Offset = &offset
	return clq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (clq *ConsentLogQuery) Unique(unique bool) *ConsentLogQuery {
	clq.ctx.Unique = &unique
	return clq
}

// Order specifies how the records should be ordered.
func (clq *ConsentLogQuery) Order(o ...consentlog.OrderOption) *ConsentLogQuery {
	clq.order = append(clq.order, o...)
	return clq
}

// First returns the first ConsentLog entity from the query.
// Returns a *NotFoundError when no ConsentLog was found.
func (clq *ConsentLogQuery) First(ctx context.Context) (*ConsentLog, error) {
	nodes, err := clq.Limit(1).All(setContextOp(ctx, clq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{consentlog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (clq *ConsentLogQuery) FirstX(ctx context.Context) *ConsentLog {
	node, err := clq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ConsentLog ID from the query.
// Returns a *NotFoundError when no ConsentLog ID was found.
func (clq *ConsentLogQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = clq.Limit(1).IDs(setContextOp(ctx, clq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{consentlog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (clq *ConsentLogQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := clq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ConsentLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ConsentLog entity is found.
// Returns a *NotFoundError when no ConsentLog entities are found.
func (clq *ConsentLogQuery) Only(ctx context.Context) (*ConsentLog, error) {
	nodes, err := clq.Limit(2).All(setContextOp(ctx, clq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{consentlog.Label}
	default:
		return nil, &NotSingularError{consentlog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (clq *ConsentLogQuery) OnlyX(ctx context.Context) *ConsentLog {
	node, err := clq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ConsentLog ID in the query.
// Returns a *NotSingularError when more than one ConsentLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (clq *ConsentLogQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = clq.Limit(2).IDs(setContextOp(ctx, clq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{consentlog.Label}
	default:
		err = &NotSingularError{consentlog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (clq *ConsentLogQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := clq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ConsentLogs.
func (clq *ConsentLogQuery) All(ctx context.Context) ([]*ConsentLog, error) {
	ctx = setContextOp(ctx, clq.ctx, ent.OpQueryAll)
	if err := clq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ConsentLog, *ConsentLogQuery]()
	return withInterceptors[[]*ConsentLog](ctx, clq, qr, clq.inters)
}

// AllX is like All, but panics if an error occurs.
func (clq *ConsentLogQuery) AllX(ctx context.Context) []*ConsentLog {
	nodes, err := clq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ConsentLog IDs.
func (clq *ConsentLogQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if clq.ctx.Unique == nil && clq.path != nil {
		clq.Unique(true)
	}
	ctx = setContextOp(ctx, clq.ctx, ent.OpQueryIDs)
	if err = clq.Select(consentlog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (clq *ConsentLogQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := clq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (clq *ConsentLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, clq.ctx, ent.OpQueryCount)
	if err := clq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, clq, querierCount[*ConsentLogQuery](), clq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (clq *ConsentLogQuery) CountX(ctx context.Context) int {
	count, err := clq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (clq *ConsentLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, clq.ctx, ent.OpQueryExist)
	switch _, err := clq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (clq *ConsentLogQuery) ExistX(ctx context.Context) bool {
	exist, err := clq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ConsentLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (clq *ConsentLogQuery) Clone() *ConsentLogQuery {
	if clq == nil {
		return nil
	}
	return &ConsentLogQuery{
		config:     clq.config,
		ctx:        clq.ctx.Clone(),
		order:      append([]consentlog.OrderOption{}, clq.order...),
		inters:     append([]Interceptor{}, clq.inters...),
		predicates: append([]predicate.ConsentLog{}, clq.predicates...),
		// clone intermediate query.
		sql:  clq.sql.Clone(),
		path: clq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ConsentLog.Query().
//		GroupBy(consentlog.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (clq *ConsentLogQuery) GroupBy(field string, fields ...string) *ConsentLogGroupBy {
	clq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ConsentLogGroupBy{build: clq}
	grbuild.flds = &clq.ctx.Fields
	grbuild.label = consentlog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ConsentLog.Query().
//		Select(consentlog.FieldCreatedAt).
//		Scan(ctx, &v)
func (clq *ConsentLogQuery) Select(fields ...string) *ConsentLogSelect {
	clq.ctx.Fields = append(clq.ctx.Fields, fields...)
	sbuild := &ConsentLogSelect{ConsentLogQuery: clq}
	sbuild.label = consentlog.Label
	sbuild.flds, sbuild.scan = &clq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ConsentLogSelect configured with the given aggregations.
func (clq *ConsentLogQuery) Aggregate(fns ...AggregateFunc) *ConsentLogSelect {
	return clq.Select().Aggregate(fns...)
}

func (clq *ConsentLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range clq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, clq); err != nil {
				return err
			}
		}
	}
	for _, f := range clq.ctx.Fields {
		if !consentlog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if clq.path != nil {
		prev, err := clq.path(ctx)
		if err != nil {
			return err
		}
		clq.sql = prev
	}
	return nil
}

func (clq *ConsentLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ConsentLog, error) {
	var (
		nodes = []*ConsentLog{}
		_spec = clq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ConsentLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ConsentLog{config: clq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, clq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (clq *ConsentLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := clq.querySpec()
	_spec.Node.Columns = clq.ctx.Fields
	if len(clq.ctx.Fields) > 0 {
		_spec.Unique = clq.ctx.Unique != nil && *clq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, clq.driver, _spec)
}

func (clq *ConsentLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(consentlog.Table, consentlog.Columns, sqlgraph.NewFieldSpec(consentlog.FieldID, field.TypeUUID))
	_spec.From = clq.sql
	if unique := clq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if clq.path != nil {
		_spec.Unique = true
	}
	if fields := clq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, consentlog.FieldID)
		for i := range fields {
			if fields[i] != consentlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := clq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := clq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := clq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := clq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (clq *ConsentLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(clq.driver.Dialect())
	t1 := builder.Table(consentlog.Table)
	columns := clq.ctx.Fields
	if len(columns) == 0 {
		columns = consentlog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if clq.sql != nil {
		selector = clq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if clq.ctx.Unique != nil && *clq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range clq.predicates {
		p(selector)
	}
	for _, p := range clq.order {
		p(selector)
	}
	if offset := clq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := clq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ConsentLogGroupBy is the group-by builder for ConsentLog entities.
type ConsentLogGroupBy struct {
	selector
	build *ConsentLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (clgb *ConsentLogGroupBy) Aggregate(fns ...AggregateFunc) *ConsentLogGroupBy {
	clgb.fns = append(clgb.fns, fns...)
	return clgb
}

// Scan applies the selector query and scans the result into the given value.
func (clgb *ConsentLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, clgb.build.ctx, ent.OpQueryGroupBy)
	if err := clgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ConsentLogQuery, *ConsentLogGroupBy](ctx, clgb.build, clgb, clgb.build.inters, v)
}

func (clgb *ConsentLogGroupBy) sqlScan(ctx context.Context, root *ConsentLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(clgb.fns))
	for _, fn := range clgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*clgb.flds)+len(clgb.fns))
		for _, f := range *clgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*clgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := clgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ConsentLogSelect is the builder for selecting fields of ConsentLog entities.
type ConsentLogSelect struct {
	*ConsentLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cls *ConsentLogSelect) Aggregate(fns ...AggregateFunc) *ConsentLogSelect {
	cls.fns = append(cls.fns, fns...)
	return cls
}

// Scan applies the selector query and scans the result into the given value.
func (cls *ConsentLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cls.ctx, ent.OpQuerySelect)
	if err := cls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ConsentLogQuery, *ConsentLogSelect](ctx, cls.ConsentLogQuery, cls, cls.inters, v)
}

func (cls *ConsentLogSelect) sqlScan(ctx context.Context, root *ConsentLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cls.fns))
	for _, fn := range cls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
