// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/witchs-lounge_backend/ent/consentlog"
)

// ConsentLog is the model entity for the ConsentLog schema.
type ConsentLog struct {
	config `json:"-"`
	// ID of the ent.
	// Global custom UUID ID
	ID uuid.UUID `json:"id,omitempty"`
	// Created time
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Updated time
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 클라이언트 발급 멱등성 키 (UUID v4). 단건/batch 공통.
	ClientConsentID uuid.UUID `json:"client_consent_id,omitempty"`
	// 기기 고유 UUID (로그인 무관 지속). 식별 주체.
	ClientID uuid.UUID `json:"client_id,omitempty"`
	// 로그인 사용자 ID. 동의 시점엔 보통 null, signin 자동연결로 나중에 채워짐. FK 없음.
	UserID *uuid.UUID `json:"user_id,omitempty"`
	// 동의 항목 (eula / privacy). 항목별 개별 레코드.
	ConsentType consentlog.ConsentType `json:"consent_type,omitempty"`
	// 동의한 정책 문서 버전 문자열 (예 "eula@2026-07-10"). 법적으로 결정적. 화이트리스트 검증 없음.
	PolicyVersion string `json:"policy_version,omitempty"`
	// 동의=true / 거부=false.
	Granted bool `json:"granted,omitempty"`
	// 입력 표시명 (익명이면 빈 문자열).
	Nickname string `json:"nickname,omitempty"`
	// 동의 시각 (클라 발생, unix seconds 수신 → time 변환).
	ConsentedAt time.Time `json:"consented_at,omitempty"`
	// 클라 버전 (증빙 맥락).
	ClientVersion string `json:"client_version,omitempty"`
	// 실행 플랫폼.
	Platform string `json:"platform,omitempty"`
	// 동의 화면 언어.
	Locale string `json:"locale,omitempty"`
	// 빌드 모드 (Inhouse/Playtest/Demo/Public/Exhibition/OnlineExhibition).
	BuildMode string `json:"build_mode,omitempty"`
	// 서버 수신 시각 (default now()). GlobalMixin created_at 과 별개 실제 컬럼.
	ReceivedAt time.Time `json:"received_at,omitempty"`
	// 파기 예정 시각. 회원탈퇴 시 탈퇴시점+3년으로 설정. 미탈퇴 계정은 null(파기 안 함).
	ExpiresAt    *time.Time `json:"expires_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ConsentLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case consentlog.FieldUserID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case consentlog.FieldGranted:
			values[i] = new(sql.NullBool)
		case consentlog.FieldConsentType, consentlog.FieldPolicyVersion, consentlog.FieldNickname, consentlog.FieldClientVersion, consentlog.FieldPlatform, consentlog.FieldLocale, consentlog.FieldBuildMode:
			values[i] = new(sql.NullString)
		case consentlog.FieldCreatedAt, consentlog.FieldUpdatedAt, consentlog.FieldConsentedAt, consentlog.FieldReceivedAt, consentlog.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		case consentlog.FieldID, consentlog.FieldClientConsentID, consentlog.FieldClientID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ConsentLog fields.
func (cl *ConsentLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case consentlog.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				cl.ID = *value
			}
		case consentlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				cl.CreatedAt = value.Time
			}
		case consentlog.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				cl.UpdatedAt = value.Time
			}
		case consentlog.FieldClientConsentID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field client_consent_id", values[i])
			} else if value != nil {
				cl.ClientConsentID = *value
			}
		case consentlog.FieldClientID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value != nil {
				cl.ClientID = *value
			}
		case consentlog.FieldUserID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				cl.UserID = new(uuid.UUID)
				*cl.UserID = *value.S.(*uuid.UUID)
			}
		case consentlog.FieldConsentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field consent_type", values[i])
			} else if value.Valid {
				cl.ConsentType = consentlog.ConsentType(value.String)
			}
		case consentlog.FieldPolicyVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field policy_version", values[i])
			} else if value.Valid {
				cl.PolicyVersion = value.String
			}
		case consentlog.FieldGranted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field granted", values[i])
			} else if value.Valid {
				cl.Granted = value.Bool
			}
		case consentlog.FieldNickname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nickname", values[i])
			} else if value.Valid {
				cl.Nickname = value.String
			}
		case consentlog.FieldConsentedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field consented_at", values[i])
			} else if value.Valid {
				cl.ConsentedAt = value.Time
			}
		case consentlog.FieldClientVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_version", values[i])
			} else if value.Valid {
				cl.ClientVersion = value.String
			}
		case consentlog.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				cl.Platform = value.String
			}
		case consentlog.FieldLocale:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locale", values[i])
			} else if value.Valid {
				cl.Locale = value.String
			}
		case consentlog.FieldBuildMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field build_mode", values[i])
			} else if value.Valid {
				cl.BuildMode = value.String
			}
		case consentlog.FieldReceivedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field received_at", values[i])
			} else if value.Valid {
				cl.ReceivedAt = value.Time
			}
		case consentlog.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				cl.ExpiresAt = new(time.Time)
				*cl.ExpiresAt = value.Time
			}
		default:
			cl.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ConsentLog.
// This includes values selected through modifiers, order, etc.
func (cl *ConsentLog) Value(name string) (ent.Value, error) {
	return cl.selectValues.Get(name)
}

// Update returns a builder for updating this ConsentLog.
// Note that you need to call ConsentLog.Unwrap() before calling this method if this ConsentLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (cl *ConsentLog) Update() *ConsentLogUpdateOne {
	return NewConsentLogClient(cl.config).UpdateOne(cl)
}

// Unwrap unwraps the ConsentLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cl *ConsentLog) Unwrap() *ConsentLog {
	_tx, ok := cl.config.driver.(*txDriver)
	if !ok {
		panic("ent: ConsentLog is not a transactional entity")
	}
	cl.config.driver = _tx.drv
	return cl
}

// String implements the fmt.Stringer.
func (cl *ConsentLog) String() string {
	var builder strings.Builder
	builder.WriteString("ConsentLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", cl.ID))
	builder.WriteString("created_at=")
	builder.WriteString(cl.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(cl.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("client_consent_id=")
	builder.WriteString(fmt.Sprintf("%v", cl.ClientConsentID))
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(fmt.Sprintf("%v", cl.ClientID))
	builder.WriteString(", ")
	if v := cl.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("consent_type=")
	builder.WriteString(fmt.Sprintf("%v", cl.ConsentType))
	builder.WriteString(", ")
	builder.WriteString("policy_version=")
	builder.WriteString(cl.PolicyVersion)
	builder.WriteString(", ")
	builder.WriteString("granted=")
	builder.WriteString(fmt.Sprintf("%v", cl.Granted))
	builder.WriteString(", ")
	builder.WriteString("nickname=")
	builder.WriteString(cl.Nickname)
	builder.WriteString(", ")
	builder.WriteString("consented_at=")
	builder.WriteString(cl.ConsentedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("client_version=")
	builder.WriteString(cl.ClientVersion)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(cl.Platform)
	builder.WriteString(", ")
	builder.WriteString("locale=")
	builder.WriteString(cl.Locale)
	builder.WriteString(", ")
	builder.WriteString("build_mode=")
	builder.WriteString(cl.BuildMode)
	builder.WriteString(", ")
	builder.WriteString("received_at=")
	builder.WriteString(cl.ReceivedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := cl.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ConsentLogs is a parsable slice of ConsentLog.
type ConsentLogs []*ConsentLog
