// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/witchs-lounge_backend/ent/eventlog"
	"github.com/witchs-lounge_backend/ent/user"
)

// EventLog is the model entity for the EventLog schema.
type EventLog struct {
	config `json:"-"`
	// ID of the ent.
	// Global custom UUID ID
	ID uuid.UUID `json:"id,omitempty"`
	// Created time
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Updated time
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 유저 ID (세션에서 도출, body 에 실리지 않음)
	UserID uuid.UUID `json:"user_id,omitempty"`
	// GameEvent enum 이름 (문자열, 예 "FirstPlay"). 서버 화이트리스트 검증 없음.
	EventKey string `json:"event_key,omitempty"`
	// 변경 전 GameEventState 이름 (문자열, 예 "Locked")
	StateBefore string `json:"state_before,omitempty"`
	// 변경 후 GameEventState 이름 (문자열, 예 "Available")
	StateAfter string `json:"state_after,omitempty"`
	// 클라 발생 시각 (클라가 unix seconds 로 전송 → time 변환). created_at 은 서버 수신 시각.
	ChangedAt time.Time `json:"changed_at,omitempty"`
	// 클라이언트 발급 멱등성 키 (UUID v4). 단건/batch 공통.
	ClientLogID *string `json:"client_log_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EventLogQuery when eager-loading is set.
	Edges        EventLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EventLogEdges holds the relations/edges for other nodes in the graph.
type EventLogEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EventLogEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EventLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case eventlog.FieldEventKey, eventlog.FieldStateBefore, eventlog.FieldStateAfter, eventlog.FieldClientLogID:
			values[i] = new(sql.NullString)
		case eventlog.FieldCreatedAt, eventlog.FieldUpdatedAt, eventlog.FieldChangedAt:
			values[i] = new(sql.NullTime)
		case eventlog.FieldID, eventlog.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EventLog fields.
func (el *EventLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case eventlog.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				el.ID = *value
			}
		case eventlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				el.CreatedAt = value.Time
			}
		case eventlog.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				el.UpdatedAt = value.Time
			}
		case eventlog.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				el.UserID = *value
			}
		case eventlog.FieldEventKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_key", values[i])
			} else if value.Valid {
				el.EventKey = value.String
			}
		case eventlog.FieldStateBefore:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state_before", values[i])
			} else if value.Valid {
				el.StateBefore = value.String
			}
		case eventlog.FieldStateAfter:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state_after", values[i])
			} else if value.Valid {
				el.StateAfter = value.String
			}
		case eventlog.FieldChangedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field changed_at", values[i])
			} else if value.Valid {
				el.ChangedAt = value.Time
			}
		case eventlog.FieldClientLogID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_log_id", values[i])
			} else if value.Valid {
				el.ClientLogID = new(string)
				*el.ClientLogID = value.String
			}
		default:
			el.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EventLog.
// This includes values selected through modifiers, order, etc.
func (el *EventLog) Value(name string) (ent.Value, error) {
	return el.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the EventLog entity.
func (el *EventLog) QueryUser() *UserQuery {
	return NewEventLogClient(el.config).QueryUser(el)
}

// Update returns a builder for updating this EventLog.
// Note that you need to call EventLog.Unwrap() before calling this method if this EventLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (el *EventLog) Update() *EventLogUpdateOne {
	return NewEventLogClient(el.config).UpdateOne(el)
}

// Unwrap unwraps the EventLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (el *EventLog) Unwrap() *EventLog {
	_tx, ok := el.config.driver.(*txDriver)
	if !ok {
		panic("ent: EventLog is not a transactional entity")
	}
	el.config.driver = _tx.drv
	return el
}

// String implements the fmt.Stringer.
func (el *EventLog) String() string {
	var builder strings.Builder
	builder.WriteString("EventLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", el.ID))
	builder.WriteString("created_at=")
	builder.WriteString(el.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(el.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", el.UserID))
	builder.WriteString(", ")
	builder.WriteString("event_key=")
	builder.WriteString(el.EventKey)
	builder.WriteString(", ")
	builder.WriteString("state_before=")
	builder.WriteString(el.StateBefore)
	builder.WriteString(", ")
	builder.WriteString("state_after=")
	builder.WriteString(el.StateAfter)
	builder.WriteString(", ")
	builder.WriteString("changed_at=")
	builder.WriteString(el.ChangedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := el.ClientLogID; v != nil {
		builder.WriteString("client_log_id=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// EventLogs is a parsable slice of EventLog.
type EventLogs []*EventLog
