// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/witchs-lounge_backend/ent/eventlog"
	"github.com/witchs-lounge_backend/ent/user"
)

// EventLogCreate is the builder for creating a EventLog entity.
type EventLogCreate struct {
	config
	mutation *EventLogMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (elc *EventLogCreate) SetCreatedAt(t time.Time) *EventLogCreate {
	elc.mutation.SetCreatedAt(t)
	return elc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (elc *EventLogCreate) SetNillableCreatedAt(t *time.Time) *EventLogCreate {
	if t != nil {
		elc.SetCreatedAt(*t)
	}
	return elc
}

// SetUpdatedAt sets the "updated_at" field.
func (elc *EventLogCreate) SetUpdatedAt(t time.Time) *EventLogCreate {
	elc.mutation.SetUpdatedAt(t)
	return elc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (elc *EventLogCreate) SetNillableUpdatedAt(t *time.Time) *EventLogCreate {
	if t != nil {
		elc.SetUpdatedAt(*t)
	}
	return elc
}

// SetUserID sets the "user_id" field.
func (elc *EventLogCreate) SetUserID(u uuid.UUID) *EventLogCreate {
	elc.mutation.SetUserID(u)
	return elc
}

// SetEventKey sets the "event_key" field.
func (elc *EventLogCreate) SetEventKey(s string) *EventLogCreate {
	elc.mutation.SetEventKey(s)
	return elc
}

// SetStateBefore sets the "state_before" field.
func (elc *EventLogCreate) SetStateBefore(s string) *EventLogCreate {
	elc.mutation.SetStateBefore(s)
	return elc
}

// SetStateAfter sets the "state_after" field.
func (elc *EventLogCreate) SetStateAfter(s string) *EventLogCreate {
	elc.mutation.SetStateAfter(s)
	return elc
}

// SetChangedAt sets the "changed_at" field.
func (elc *EventLogCreate) SetChangedAt(t time.Time) *EventLogCreate {
	elc.mutation.SetChangedAt(t)
	return elc
}

// SetClientLogID sets the "client_log_id" field.
func (elc *EventLogCreate) SetClientLogID(s string) *EventLogCreate {
	elc.mutation.SetClientLogID(s)
	return elc
}

// SetNillableClientLogID sets the "client_log_id" field if the given value is not nil.
func (elc *EventLogCreate) SetNillableClientLogID(s *string) *EventLogCreate {
	if s != nil {
		elc.SetClientLogID(*s)
	}
	return elc
}

// SetID sets the "id" field.
func (elc *EventLogCreate) SetID(u uuid.UUID) *EventLogCreate {
	elc.mutation.SetID(u)
	return elc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (elc *EventLogCreate) SetNillableID(u *uuid.UUID) *EventLogCreate {
	if u != nil {
		elc.SetID(*u)
	}
	return elc
}

// SetUser sets the "user" edge to the User entity.
func (elc *EventLogCreate) SetUser(u *User) *EventLogCreate {
	return elc.SetUserID(u.ID)
}

// Mutation returns the EventLogMutation object of the builder.
func (elc *EventLogCreate) Mutation() *EventLogMutation {
	return elc.mutation
}

// Save creates the EventLog in the database.
func (elc *EventLogCreate) Save(ctx context.Context) (*EventLog, error) {
	elc.defaults()
	return withHooks(ctx, elc.sqlSave, elc.mutation, elc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (elc *EventLogCreate) SaveX(ctx context.Context) *EventLog {
	v, err := elc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (elc *EventLogCreate) Exec(ctx context.Context) error {
	_, err := elc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (elc *EventLogCreate) ExecX(ctx context.Context) {
	if err := elc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (elc *EventLogCreate) defaults() {
	if _, ok := elc.mutation.CreatedAt(); !ok {
		v := eventlog.DefaultCreatedAt()
		elc.mutation.SetCreatedAt(v)
	}
	if _, ok := elc.mutation.UpdatedAt(); !ok {
		v := eventlog.DefaultUpdatedAt()
		elc.mutation.SetUpdatedAt(v)
	}
	if _, ok := elc.mutation.ID(); !ok {
		v := eventlog.DefaultID()
		elc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (elc *EventLogCreate) check() error {
	if _, ok := elc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EventLog.created_at"`)}
	}
	if _, ok := elc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EventLog.updated_at"`)}
	}
	if _, ok := elc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "EventLog.user_id"`)}
	}
	if _, ok := elc.mutation.EventKey(); !ok {
		return &ValidationError{Name: "event_key", err: errors.New(`ent: missing required field "EventLog.event_key"`)}
	}
	if _, ok := elc.mutation.StateBefore(); !ok {
		return &ValidationError{Name: "state_before", err: errors.New(`ent: missing required field "EventLog.state_before"`)}
	}
	if _, ok := elc.mutation.StateAfter(); !ok {
		return &ValidationError{Name: "state_after", err: errors.New(`ent: missing required field "EventLog.state_after"`)}
	}
	if _, ok := elc.mutation.ChangedAt(); !ok {
		return &ValidationError{Name: "changed_at", err: errors.New(`ent: missing required field "EventLog.changed_at"`)}
	}
	if v, ok := elc.mutation.ClientLogID(); ok {
		if err := eventlog.ClientLogIDValidator(v); err != nil {
			return &ValidationError{Name: "client_log_id", err: fmt.Errorf(`ent: validator failed for field "EventLog.client_log_id": %w`, err)}
		}
	}
	if len(elc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "EventLog.user"`)}
	}
	return nil
}

func (elc *EventLogCreate) sqlSave(ctx context.Context) (*EventLog, error) {
	if err := elc.check(); err != nil {
		return nil, err
	}
	_node, _spec := elc.createSpec()
	if err := sqlgraph.CreateNode(ctx, elc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	elc.mutation.id = &_node.ID
	elc.mutation.done = true
	return _node, nil
}

func (elc *EventLogCreate) createSpec() (*EventLog, *sqlgraph.CreateSpec) {
	var (
		_node = &EventLog{config: elc.config}
		_spec = sqlgraph.NewCreateSpec(eventlog.Table, sqlgraph.NewFieldSpec(eventlog.FieldID, field.TypeUUID))
	)
	if id, ok := elc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := elc.mutation.CreatedAt(); ok {
		_spec.SetField(eventlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := elc.mutation.UpdatedAt(); ok {
		_spec.SetField(eventlog.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := elc.mutation.EventKey(); ok {
		_spec.SetField(eventlog.FieldEventKey, field.TypeString, value)
		_node.EventKey = value
	}
	if value, ok := elc.mutation.StateBefore(); ok {
		_spec.SetField(eventlog.FieldStateBefore, field.TypeString, value)
		_node.StateBefore = value
	}
	if value, ok := elc.mutation.StateAfter(); ok {
		_spec.SetField(eventlog.FieldStateAfter, field.TypeString, value)
		_node.StateAfter = value
	}
	if value, ok := elc.mutation.ChangedAt(); ok {
		_spec.SetField(eventlog.FieldChangedAt, field.TypeTime, value)
		_node.ChangedAt = value
	}
	if value, ok := elc.mutation.ClientLogID(); ok {
		_spec.SetField(eventlog.FieldClientLogID, field.TypeString, value)
		_node.ClientLogID = &value
	}
	if nodes := elc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventlog.UserTable,
			Columns: []string{eventlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EventLogCreateBulk is the builder for creating many EventLog entities in bulk.
type EventLogCreateBulk struct {
	config
	err      error
	builders []*EventLogCreate
}

// Save creates the EventLog entities in the database.
func (elcb *EventLogCreateBulk) Save(ctx context.Context) ([]*EventLog, error) {
	if elcb.err != nil {
		return nil, elcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(elcb.builders))
	nodes := make([]*EventLog, len(elcb.builders))
	mutators := make([]Mutator, len(elcb.builders))
	for i := range elcb.builders {
		func(i int, root context.Context) {
			builder := elcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, elcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, elcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, elcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (elcb *EventLogCreateBulk) SaveX(ctx context.Context) []*EventLog {
	v, err := elcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (elcb *EventLogCreateBulk) Exec(ctx context.Context) error {
	_, err := elcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (elcb *EventLogCreateBulk) ExecX(ctx context.Context) {
	if err := elcb.Exec(ctx); err != nil {
		panic(err)
	}
}
