// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/witchs-lounge_backend/ent/eventlog"
	"github.com/witchs-lounge_backend/ent/predicate"
	"github.com/witchs-lounge_backend/ent/user"
)

// EventLogUpdate is the builder for updating EventLog entities.
type EventLogUpdate struct {
	config
	hooks    []Hook
	mutation *EventLogMutation
}

// Where appends a list predicates to the EventLogUpdate builder.
func (elu *EventLogUpdate) Where(ps ...predicate.EventLog) *EventLogUpdate {
	elu.mutation.Where(ps...)
	return elu
}

// SetUpdatedAt sets the "updated_at" field.
func (elu *EventLogUpdate) SetUpdatedAt(t time.Time) *EventLogUpdate {
	elu.mutation.SetUpdatedAt(t)
	return elu
}

// SetUserID sets the "user_id" field.
func (elu *EventLogUpdate) SetUserID(u uuid.UUID) *EventLogUpdate {
	elu.mutation.SetUserID(u)
	return elu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (elu *EventLogUpdate) SetNillableUserID(u *uuid.UUID) *EventLogUpdate {
	if u != nil {
		elu.SetUserID(*u)
	}
	return elu
}

// SetEventKey sets the "event_key" field.
func (elu *EventLogUpdate) SetEventKey(s string) *EventLogUpdate {
	elu.mutation.SetEventKey(s)
	return elu
}

// SetNillableEventKey sets the "event_key" field if the given value is not nil.
func (elu *EventLogUpdate) SetNillableEventKey(s *string) *EventLogUpdate {
	if s != nil {
		elu.SetEventKey(*s)
	}
	return elu
}

// SetStateBefore sets the "state_before" field.
func (elu *EventLogUpdate) SetStateBefore(s string) *EventLogUpdate {
	elu.mutation.SetStateBefore(s)
	return elu
}

// SetNillableStateBefore sets the "state_before" field if the given value is not nil.
func (elu *EventLogUpdate) SetNillableStateBefore(s *string) *EventLogUpdate {
	if s != nil {
		elu.SetStateBefore(*s)
	}
	return elu
}

// SetStateAfter sets the "state_after" field.
func (elu *EventLogUpdate) SetStateAfter(s string) *EventLogUpdate {
	elu.mutation.SetStateAfter(s)
	return elu
}

// SetNillableStateAfter sets the "state_after" field if the given value is not nil.
func (elu *EventLogUpdate) SetNillableStateAfter(s *string) *EventLogUpdate {
	if s != nil {
		elu.SetStateAfter(*s)
	}
	return elu
}

// SetChangedAt sets the "changed_at" field.
func (elu *EventLogUpdate) SetChangedAt(t time.Time) *EventLogUpdate {
	elu.mutation.SetChangedAt(t)
	return elu
}

// SetNillableChangedAt sets the "changed_at" field if the given value is not nil.
func (elu *EventLogUpdate) SetNillableChangedAt(t *time.Time) *EventLogUpdate {
	if t != nil {
		elu.SetChangedAt(*t)
	}
	return elu
}

// SetClientLogID sets the "client_log_id" field.
func (elu *EventLogUpdate) SetClientLogID(s string) *EventLogUpdate {
	elu.mutation.SetClientLogID(s)
	return elu
}

// SetNillableClientLogID sets the "client_log_id" field if the given value is not nil.
func (elu *EventLogUpdate) SetNillableClientLogID(s *string) *EventLogUpdate {
	if s != nil {
		elu.SetClientLogID(*s)
	}
	return elu
}

// ClearClientLogID clears the value of the "client_log_id" field.
func (elu *EventLogUpdate) ClearClientLogID() *EventLogUpdate {
	elu.mutation.ClearClientLogID()
	return elu
}

// SetUser sets the "user" edge to the User entity.
func (elu *EventLogUpdate) SetUser(u *User) *EventLogUpdate {
	return elu.SetUserID(u.ID)
}

// Mutation returns the EventLogMutation object of the builder.
func (elu *EventLogUpdate) Mutation() *EventLogMutation {
	return elu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (elu *EventLogUpdate) ClearUser() *EventLogUpdate {
	elu.mutation.ClearUser()
	return elu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (elu *EventLogUpdate) Save(ctx context.Context) (int, error) {
	elu.defaults()
	return withHooks(ctx, elu.sqlSave, elu.mutation, elu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (elu *EventLogUpdate) SaveX(ctx context.Context) int {
	affected, err := elu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (elu *EventLogUpdate) Exec(ctx context.Context) error {
	_, err := elu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (elu *EventLogUpdate) ExecX(ctx context.Context) {
	if err := elu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (elu *EventLogUpdate) defaults() {
	if _, ok := elu.mutation.UpdatedAt(); !ok {
		v := eventlog.UpdateDefaultUpdatedAt()
		elu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (elu *EventLogUpdate) check() error {
	if v, ok := elu.mutation.ClientLogID(); ok {
		if err := eventlog.ClientLogIDValidator(v); err != nil {
			return &ValidationError{Name: "client_log_id", err: fmt.Errorf(`ent: validator failed for field "EventLog.client_log_id": %w`, err)}
		}
	}
	if elu.mutation.UserCleared() && len(elu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EventLog.user"`)
	}
	return nil
}

func (elu *EventLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := elu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(eventlog.Table, eventlog.Columns, sqlgraph.NewFieldSpec(eventlog.FieldID, field.TypeUUID))
	if ps := elu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := elu.mutation.UpdatedAt(); ok {
		_spec.SetField(eventlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := elu.mutation.EventKey(); ok {
		_spec.SetField(eventlog.FieldEventKey, field.TypeString, value)
	}
	if value, ok := elu.mutation.StateBefore(); ok {
		_spec.SetField(eventlog.FieldStateBefore, field.TypeString, value)
	}
	if value, ok := elu.mutation.StateAfter(); ok {
		_spec.SetField(eventlog.FieldStateAfter, field.TypeString, value)
	}
	if value, ok := elu.mutation.ChangedAt(); ok {
		_spec.SetField(eventlog.FieldChangedAt, field.TypeTime, value)
	}
	if value, ok := elu.mutation.ClientLogID(); ok {
		_spec.SetField(eventlog.FieldClientLogID, field.TypeString, value)
	}
	if elu.mutation.ClientLogIDCleared() {
		_spec.ClearField(eventlog.FieldClientLogID, field.TypeString)
	}
	if elu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventlog.UserTable,
			Columns: []string{eventlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := elu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventlog.UserTable,
			Columns: []string{eventlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, elu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{eventlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	elu.mutation.done = true
	return n, nil
}

// EventLogUpdateOne is the builder for updating a single EventLog entity.
type EventLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventLogMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (eluo *EventLogUpdateOne) SetUpdatedAt(t time.Time) *EventLogUpdateOne {
	eluo.mutation.SetUpdatedAt(t)
	return eluo
}

// SetUserID sets the "user_id" field.
func (eluo *EventLogUpdateOne) SetUserID(u uuid.UUID) *EventLogUpdateOne {
	eluo.mutation.SetUserID(u)
	return eluo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (eluo *EventLogUpdateOne) SetNillableUserID(u *uuid.UUID) *EventLogUpdateOne {
	if u != nil {
		eluo.SetUserID(*u)
	}
	return eluo
}

// SetEventKey sets the "event_key" field.
func (eluo *EventLogUpdateOne) SetEventKey(s string) *EventLogUpdateOne {
	eluo.mutation.SetEventKey(s)
	return eluo
}

// SetNillableEventKey sets the "event_key" field if the given value is not nil.
func (eluo *EventLogUpdateOne) SetNillableEventKey(s *string) *EventLogUpdateOne {
	if s != nil {
		eluo.SetEventKey(*s)
	}
	return eluo
}

// SetStateBefore sets the "state_before" field.
func (eluo *EventLogUpdateOne) SetStateBefore(s string) *EventLogUpdateOne {
	eluo.mutation.SetStateBefore(s)
	return eluo
}

// SetNillableStateBefore sets the "state_before" field if the given value is not nil.
func (eluo *EventLogUpdateOne) SetNillableStateBefore(s *string) *EventLogUpdateOne {
	if s != nil {
		eluo.SetStateBefore(*s)
	}
	return eluo
}

// SetStateAfter sets the "state_after" field.
func (eluo *EventLogUpdateOne) SetStateAfter(s string) *EventLogUpdateOne {
	eluo.mutation.SetStateAfter(s)
	return eluo
}

// SetNillableStateAfter sets the "state_after" field if the given value is not nil.
func (eluo *EventLogUpdateOne) SetNillableStateAfter(s *string) *EventLogUpdateOne {
	if s != nil {
		eluo.SetStateAfter(*s)
	}
	return eluo
}

// SetChangedAt sets the "changed_at" field.
func (eluo *EventLogUpdateOne) SetChangedAt(t time.Time) *EventLogUpdateOne {
	eluo.mutation.SetChangedAt(t)
	return eluo
}

// SetNillableChangedAt sets the "changed_at" field if the given value is not nil.
func (eluo *EventLogUpdateOne) SetNillableChangedAt(t *time.Time) *EventLogUpdateOne {
	if t != nil {
		eluo.SetChangedAt(*t)
	}
	return eluo
}

// SetClientLogID sets the "client_log_id" field.
func (eluo *EventLogUpdateOne) SetClientLogID(s string) *EventLogUpdateOne {
	eluo.mutation.SetClientLogID(s)
	return eluo
}

// SetNillableClientLogID sets the "client_log_id" field if the given value is not nil.
func (eluo *EventLogUpdateOne) SetNillableClientLogID(s *string) *EventLogUpdateOne {
	if s != nil {
		eluo.SetClientLogID(*s)
	}
	return eluo
}

// ClearClientLogID clears the value of the "client_log_id" field.
func (eluo *EventLogUpdateOne) ClearClientLogID() *EventLogUpdateOne {
	eluo.mutation.ClearClientLogID()
	return eluo
}

// SetUser sets the "user" edge to the User entity.
func (eluo *EventLogUpdateOne) SetUser(u *User) *EventLogUpdateOne {
	return eluo.SetUserID(u.ID)
}

// Mutation returns the EventLogMutation object of the builder.
func (eluo *EventLogUpdateOne) Mutation() *EventLogMutation {
	return eluo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (eluo *EventLogUpdateOne) ClearUser() *EventLogUpdateOne {
	eluo.mutation.ClearUser()
	return eluo
}

// Where appends a list predicates to the EventLogUpdate builder.
func (eluo *EventLogUpdateOne) Where(ps ...predicate.EventLog) *EventLogUpdateOne {
	eluo.mutation.Where(ps...)
	return eluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (eluo *EventLogUpdateOne) Select(field string, fields ...string) *EventLogUpdateOne {
	eluo.fields = append([]string{field}, fields...)
	return eluo
}

// Save executes the query and returns the updated EventLog entity.
func (eluo *EventLogUpdateOne) Save(ctx context.Context) (*EventLog, error) {
	eluo.defaults()
	return withHooks(ctx, eluo.sqlSave, eluo.mutation, eluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eluo *EventLogUpdateOne) SaveX(ctx context.Context) *EventLog {
	node, err := eluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (eluo *EventLogUpdateOne) Exec(ctx context.Context) error {
	_, err := eluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eluo *EventLogUpdateOne) ExecX(ctx context.Context) {
	if err := eluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (eluo *EventLogUpdateOne) defaults() {
	if _, ok := eluo.mutation.UpdatedAt(); !ok {
		v := eventlog.UpdateDefaultUpdatedAt()
		eluo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eluo *EventLogUpdateOne) check() error {
	if v, ok := eluo.mutation.ClientLogID(); ok {
		if err := eventlog.ClientLogIDValidator(v); err != nil {
			return &ValidationError{Name: "client_log_id", err: fmt.Errorf(`ent: validator failed for field "EventLog.client_log_id": %w`, err)}
		}
	}
	if eluo.mutation.UserCleared() && len(eluo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EventLog.user"`)
	}
	return nil
}

func (eluo *EventLogUpdateOne) sqlSave(ctx context.Context) (_node *EventLog, err error) {
	if err := eluo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(eventlog.Table, eventlog.Columns, sqlgraph.NewFieldSpec(eventlog.FieldID, field.TypeUUID))
	id, ok := eluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EventLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := eluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, eventlog.FieldID)
		for _, f := range fields {
			if !eventlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != eventlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := eluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eluo.mutation.UpdatedAt(); ok {
		_spec.SetField(eventlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := eluo.mutation.EventKey(); ok {
		_spec.SetField(eventlog.FieldEventKey, field.TypeString, value)
	}
	if value, ok := eluo.mutation.StateBefore(); ok {
		_spec.SetField(eventlog.FieldStateBefore, field.TypeString, value)
	}
	if value, ok := eluo.mutation.StateAfter(); ok {
		_spec.SetField(eventlog.FieldStateAfter, field.TypeString, value)
	}
	if value, ok := eluo.mutation.ChangedAt(); ok {
		_spec.SetField(eventlog.FieldChangedAt, field.TypeTime, value)
	}
	if value, ok := eluo.mutation.ClientLogID(); ok {
		_spec.SetField(eventlog.FieldClientLogID, field.TypeString, value)
	}
	if eluo.mutation.ClientLogIDCleared() {
		_spec.ClearField(eventlog.FieldClientLogID, field.TypeString)
	}
	if eluo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventlog.UserTable,
			Columns: []string{eventlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eluo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventlog.UserTable,
			Columns: []string{eventlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EventLog{config: eluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, eluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{eventlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	eluo.mutation.done = true
	return _node, nil
}
