// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/witchs-lounge_backend/ent/tlevel"
)

// TLevelCreate is the builder for creating a TLevel entity.
type TLevelCreate struct {
	config
	mutation *TLevelMutation
	hooks    []Hook
}

// SetRequireExp sets the "require_exp" field.
func (tc *TLevelCreate) SetRequireExp(i int) *TLevelCreate {
	tc.mutation.SetRequireExp(i)
	return tc
}

// SetID sets the "id" field.
func (tc *TLevelCreate) SetID(i int) *TLevelCreate {
	tc.mutation.SetID(i)
	return tc
}

// Mutation returns the TLevelMutation object of the builder.
func (tc *TLevelCreate) Mutation() *TLevelMutation {
	return tc.mutation
}

// Save creates the TLevel in the database.
func (tc *TLevelCreate) Save(ctx context.Context) (*TLevel, error) {
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TLevelCreate) SaveX(ctx context.Context) *TLevel {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TLevelCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TLevelCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TLevelCreate) check() error {
	if _, ok := tc.mutation.RequireExp(); !ok {
		return &ValidationError{Name: "require_exp", err: errors.New(`ent: missing required field "TLevel.require_exp"`)}
	}
	return nil
}

func (tc *TLevelCreate) sqlSave(ctx context.Context) (*TLevel, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TLevelCreate) createSpec() (*TLevel, *sqlgraph.CreateSpec) {
	var (
		_node = &TLevel{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(tlevel.Table, sqlgraph.NewFieldSpec(tlevel.FieldID, field.TypeInt))
	)
	if id, ok := tc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := tc.mutation.RequireExp(); ok {
		_spec.SetField(tlevel.FieldRequireExp, field.TypeInt, value)
		_node.RequireExp = value
	}
	return _node, _spec
}

// TLevelCreateBulk is the builder for creating many TLevel entities in bulk.
type TLevelCreateBulk struct {
	config
	err      error
	builders []*TLevelCreate
}

// Save creates the TLevel entities in the database.
func (tcb *TLevelCreateBulk) Save(ctx context.Context) ([]*TLevel, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*TLevel, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TLevelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TLevelCreateBulk) SaveX(ctx context.Context) []*TLevel {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TLevelCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TLevelCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
