// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/witchs-lounge_backend/ent/predicate"
	"github.com/witchs-lounge_backend/ent/tlevel"
)

// TLevelUpdate is the builder for updating TLevel entities.
type TLevelUpdate struct {
	config
	hooks    []Hook
	mutation *TLevelMutation
}

// Where appends a list predicates to the TLevelUpdate builder.
func (tu *TLevelUpdate) Where(ps ...predicate.TLevel) *TLevelUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetRequireExp sets the "require_exp" field.
func (tu *TLevelUpdate) SetRequireExp(i int) *TLevelUpdate {
	tu.mutation.ResetRequireExp()
	tu.mutation.SetRequireExp(i)
	return tu
}

// SetNillableRequireExp sets the "require_exp" field if the given value is not nil.
func (tu *TLevelUpdate) SetNillableRequireExp(i *int) *TLevelUpdate {
	if i != nil {
		tu.SetRequireExp(*i)
	}
	return tu
}

// AddRequireExp adds i to the "require_exp" field.
func (tu *TLevelUpdate) AddRequireExp(i int) *TLevelUpdate {
	tu.mutation.AddRequireExp(i)
	return tu
}

// Mutation returns the TLevelMutation object of the builder.
func (tu *TLevelUpdate) Mutation() *TLevelMutation {
	return tu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TLevelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TLevelUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TLevelUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TLevelUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tu *TLevelUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(tlevel.Table, tlevel.Columns, sqlgraph.NewFieldSpec(tlevel.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.RequireExp(); ok {
		_spec.SetField(tlevel.FieldRequireExp, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedRequireExp(); ok {
		_spec.AddField(tlevel.FieldRequireExp, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tlevel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TLevelUpdateOne is the builder for updating a single TLevel entity.
type TLevelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TLevelMutation
}

// SetRequireExp sets the "require_exp" field.
func (tuo *TLevelUpdateOne) SetRequireExp(i int) *TLevelUpdateOne {
	tuo.mutation.ResetRequireExp()
	tuo.mutation.SetRequireExp(i)
	return tuo
}

// SetNillableRequireExp sets the "require_exp" field if the given value is not nil.
func (tuo *TLevelUpdateOne) SetNillableRequireExp(i *int) *TLevelUpdateOne {
	if i != nil {
		tuo.SetRequireExp(*i)
	}
	return tuo
}

// AddRequireExp adds i to the "require_exp" field.
func (tuo *TLevelUpdateOne) AddRequireExp(i int) *TLevelUpdateOne {
	tuo.mutation.AddRequireExp(i)
	return tuo
}

// Mutation returns the TLevelMutation object of the builder.
func (tuo *TLevelUpdateOne) Mutation() *TLevelMutation {
	return tuo.mutation
}

// Where appends a list predicates to the TLevelUpdate builder.
func (tuo *TLevelUpdateOne) Where(ps ...predicate.TLevel) *TLevelUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TLevelUpdateOne) Select(field string, fields ...string) *TLevelUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated TLevel entity.
func (tuo *TLevelUpdateOne) Save(ctx context.Context) (*TLevel, error) {
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TLevelUpdateOne) SaveX(ctx context.Context) *TLevel {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TLevelUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TLevelUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tuo *TLevelUpdateOne) sqlSave(ctx context.Context) (_node *TLevel, err error) {
	_spec := sqlgraph.NewUpdateSpec(tlevel.Table, tlevel.Columns, sqlgraph.NewFieldSpec(tlevel.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TLevel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tlevel.FieldID)
		for _, f := range fields {
			if !tlevel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tlevel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.RequireExp(); ok {
		_spec.SetField(tlevel.FieldRequireExp, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedRequireExp(); ok {
		_spec.AddField(tlevel.FieldRequireExp, field.TypeInt, value)
	}
	_node = &TLevel{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tlevel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
