// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/witchs-lounge_backend/ent/tlevel"
)

// TLevel is the model entity for the TLevel schema.
type TLevel struct {
	config `json:"-"`
	// ID of the ent.
	// 레벨
	ID int `json:"id,omitempty"`
	// 요구 경험치
	RequireExp   int `json:"require_exp,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TLevel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tlevel.FieldID, tlevel.FieldRequireExp:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TLevel fields.
func (t *TLevel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tlevel.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			t.ID = int(value.Int64)
		case tlevel.FieldRequireExp:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field require_exp", values[i])
			} else if value.Valid {
				t.RequireExp = int(value.Int64)
			}
		default:
			t.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TLevel.
// This includes values selected through modifiers, order, etc.
func (t *TLevel) Value(name string) (ent.Value, error) {
	return t.selectValues.Get(name)
}

// Update returns a builder for updating this TLevel.
// Note that you need to call TLevel.Unwrap() before calling this method if this TLevel
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *TLevel) Update() *TLevelUpdateOne {
	return NewTLevelClient(t.config).UpdateOne(t)
}

// Unwrap unwraps the TLevel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *TLevel) Unwrap() *TLevel {
	_tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: TLevel is not a transactional entity")
	}
	t.config.driver = _tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *TLevel) String() string {
	var builder strings.Builder
	builder.WriteString("TLevel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", t.ID))
	builder.WriteString("require_exp=")
	builder.WriteString(fmt.Sprintf("%v", t.RequireExp))
	builder.WriteByte(')')
	return builder.String()
}

// TLevels is a parsable slice of TLevel.
type TLevels []*TLevel
