// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/witchs-lounge_backend/ent/predicate"
	"github.com/witchs-lounge_backend/ent/trank"
)

// TRankUpdate is the builder for updating TRank entities.
type TRankUpdate struct {
	config
	hooks    []Hook
	mutation *TRankMutation
}

// Where appends a list predicates to the TRankUpdate builder.
func (tu *TRankUpdate) Where(ps ...predicate.TRank) *TRankUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetCoefficient sets the "coefficient" field.
func (tu *TRankUpdate) SetCoefficient(f float32) *TRankUpdate {
	tu.mutation.ResetCoefficient()
	tu.mutation.SetCoefficient(f)
	return tu
}

// SetNillableCoefficient sets the "coefficient" field if the given value is not nil.
func (tu *TRankUpdate) SetNillableCoefficient(f *float32) *TRankUpdate {
	if f != nil {
		tu.SetCoefficient(*f)
	}
	return tu
}

// AddCoefficient adds f to the "coefficient" field.
func (tu *TRankUpdate) AddCoefficient(f float32) *TRankUpdate {
	tu.mutation.AddCoefficient(f)
	return tu
}

// Mutation returns the TRankMutation object of the builder.
func (tu *TRankUpdate) Mutation() *TRankMutation {
	return tu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TRankUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TRankUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TRankUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TRankUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tu *TRankUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(trank.Table, trank.Columns, sqlgraph.NewFieldSpec(trank.FieldID, field.TypeString))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Coefficient(); ok {
		_spec.SetField(trank.FieldCoefficient, field.TypeFloat32, value)
	}
	if value, ok := tu.mutation.AddedCoefficient(); ok {
		_spec.AddField(trank.FieldCoefficient, field.TypeFloat32, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{trank.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TRankUpdateOne is the builder for updating a single TRank entity.
type TRankUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TRankMutation
}

// SetCoefficient sets the "coefficient" field.
func (tuo *TRankUpdateOne) SetCoefficient(f float32) *TRankUpdateOne {
	tuo.mutation.ResetCoefficient()
	tuo.mutation.SetCoefficient(f)
	return tuo
}

// SetNillableCoefficient sets the "coefficient" field if the given value is not nil.
func (tuo *TRankUpdateOne) SetNillableCoefficient(f *float32) *TRankUpdateOne {
	if f != nil {
		tuo.SetCoefficient(*f)
	}
	return tuo
}

// AddCoefficient adds f to the "coefficient" field.
func (tuo *TRankUpdateOne) AddCoefficient(f float32) *TRankUpdateOne {
	tuo.mutation.AddCoefficient(f)
	return tuo
}

// Mutation returns the TRankMutation object of the builder.
func (tuo *TRankUpdateOne) Mutation() *TRankMutation {
	return tuo.mutation
}

// Where appends a list predicates to the TRankUpdate builder.
func (tuo *TRankUpdateOne) Where(ps ...predicate.TRank) *TRankUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TRankUpdateOne) Select(field string, fields ...string) *TRankUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated TRank entity.
func (tuo *TRankUpdateOne) Save(ctx context.Context) (*TRank, error) {
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TRankUpdateOne) SaveX(ctx context.Context) *TRank {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TRankUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TRankUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tuo *TRankUpdateOne) sqlSave(ctx context.Context) (_node *TRank, err error) {
	_spec := sqlgraph.NewUpdateSpec(trank.Table, trank.Columns, sqlgraph.NewFieldSpec(trank.FieldID, field.TypeString))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TRank.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, trank.FieldID)
		for _, f := range fields {
			if !trank.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != trank.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Coefficient(); ok {
		_spec.SetField(trank.FieldCoefficient, field.TypeFloat32, value)
	}
	if value, ok := tuo.mutation.AddedCoefficient(); ok {
		_spec.AddField(trank.FieldCoefficient, field.TypeFloat32, value)
	}
	_node = &TRank{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{trank.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
