// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/witchs-lounge_backend/ent/trank"
)

// TRankCreate is the builder for creating a TRank entity.
type TRankCreate struct {
	config
	mutation *TRankMutation
	hooks    []Hook
}

// SetCoefficient sets the "coefficient" field.
func (tc *TRankCreate) SetCoefficient(f float32) *TRankCreate {
	tc.mutation.SetCoefficient(f)
	return tc
}

// SetID sets the "id" field.
func (tc *TRankCreate) SetID(s string) *TRankCreate {
	tc.mutation.SetID(s)
	return tc
}

// Mutation returns the TRankMutation object of the builder.
func (tc *TRankCreate) Mutation() *TRankMutation {
	return tc.mutation
}

// Save creates the TRank in the database.
func (tc *TRankCreate) Save(ctx context.Context) (*TRank, error) {
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TRankCreate) SaveX(ctx context.Context) *TRank {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TRankCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TRankCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TRankCreate) check() error {
	if _, ok := tc.mutation.Coefficient(); !ok {
		return &ValidationError{Name: "coefficient", err: errors.New(`ent: missing required field "TRank.coefficient"`)}
	}
	return nil
}

func (tc *TRankCreate) sqlSave(ctx context.Context) (*TRank, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected TRank.ID type: %T", _spec.ID.Value)
		}
	}
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TRankCreate) createSpec() (*TRank, *sqlgraph.CreateSpec) {
	var (
		_node = &TRank{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(trank.Table, sqlgraph.NewFieldSpec(trank.FieldID, field.TypeString))
	)
	if id, ok := tc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := tc.mutation.Coefficient(); ok {
		_spec.SetField(trank.FieldCoefficient, field.TypeFloat32, value)
		_node.Coefficient = value
	}
	return _node, _spec
}

// TRankCreateBulk is the builder for creating many TRank entities in bulk.
type TRankCreateBulk struct {
	config
	err      error
	builders []*TRankCreate
}

// Save creates the TRank entities in the database.
func (tcb *TRankCreateBulk) Save(ctx context.Context) ([]*TRank, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*TRank, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TRankMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TRankCreateBulk) SaveX(ctx context.Context) []*TRank {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TRankCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TRankCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
