// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/witchs-lounge_backend/ent/trank"
)

// TRank is the model entity for the TRank schema.
type TRank struct {
	config `json:"-"`
	// ID of the ent.
	// 랭크
	ID string `json:"id,omitempty"`
	// 경험치 계수
	Coefficient  float32 `json:"coefficient,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TRank) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case trank.FieldCoefficient:
			values[i] = new(sql.NullFloat64)
		case trank.FieldID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TRank fields.
func (t *TRank) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case trank.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				t.ID = value.String
			}
		case trank.FieldCoefficient:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field coefficient", values[i])
			} else if value.Valid {
				t.Coefficient = float32(value.Float64)
			}
		default:
			t.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TRank.
// This includes values selected through modifiers, order, etc.
func (t *TRank) Value(name string) (ent.Value, error) {
	return t.selectValues.Get(name)
}

// Update returns a builder for updating this TRank.
// Note that you need to call TRank.Unwrap() before calling this method if this TRank
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *TRank) Update() *TRankUpdateOne {
	return NewTRankClient(t.config).UpdateOne(t)
}

// Unwrap unwraps the TRank entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *TRank) Unwrap() *TRank {
	_tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: TRank is not a transactional entity")
	}
	t.config.driver = _tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *TRank) String() string {
	var builder strings.Builder
	builder.WriteString("TRank(")
	builder.WriteString(fmt.Sprintf("id=%v, ", t.ID))
	builder.WriteString("coefficient=")
	builder.WriteString(fmt.Sprintf("%v", t.Coefficient))
	builder.WriteByte(')')
	return builder.String()
}

// TRanks is a parsable slice of TRank.
type TRanks []*TRank
