// Code generated by ent, DO NOT EDIT.

package eventlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/witchs-lounge_backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.EventLog {
	return predicate.EventLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.EventLog {
	return predicate.EventLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.EventLog {
	return predicate.EventLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.EventLog {
	return predicate.EventLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.EventLog {
	return predicate.EventLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.EventLog {
	return predicate.EventLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.EventLog {
	return predicate.EventLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.EventLog {
	return predicate.EventLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.EventLog {
	return predicate.EventLog(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.EventLog {
	return predicate.EventLog(sql.FieldEQ(FieldUserID, v))
}

// EventKey applies equality check predicate on the "event_key" field. It's identical to EventKeyEQ.
func EventKey(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldEQ(FieldEventKey, v))
}

// StateBefore applies equality check predicate on the "state_before" field. It's identical to StateBeforeEQ.
func StateBefore(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldEQ(FieldStateBefore, v))
}

// StateAfter applies equality check predicate on the "state_after" field. It's identical to StateAfterEQ.
func StateAfter(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldEQ(FieldStateAfter, v))
}

// ChangedAt applies equality check predicate on the "changed_at" field. It's identical to ChangedAtEQ.
func ChangedAt(v time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldEQ(FieldChangedAt, v))
}

// ClientLogID applies equality check predicate on the "client_log_id" field. It's identical to ClientLogIDEQ.
func ClientLogID(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldEQ(FieldClientLogID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.EventLog {
	return predicate.EventLog(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.EventLog {
	return predicate.EventLog(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.EventLog {
	return predicate.EventLog(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.EventLog {
	return predicate.EventLog(sql.FieldNotIn(FieldUserID, vs...))
}

// EventKeyEQ applies the EQ predicate on the "event_key" field.
func EventKeyEQ(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldEQ(FieldEventKey, v))
}

// EventKeyNEQ applies the NEQ predicate on the "event_key" field.
func EventKeyNEQ(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldNEQ(FieldEventKey, v))
}

// EventKeyIn applies the In predicate on the "event_key" field.
func EventKeyIn(vs ...string) predicate.EventLog {
	return predicate.EventLog(sql.FieldIn(FieldEventKey, vs...))
}

// EventKeyNotIn applies the NotIn predicate on the "event_key" field.
func EventKeyNotIn(vs ...string) predicate.EventLog {
	return predicate.EventLog(sql.FieldNotIn(FieldEventKey, vs...))
}

// EventKeyGT applies the GT predicate on the "event_key" field.
func EventKeyGT(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldGT(FieldEventKey, v))
}

// EventKeyGTE applies the GTE predicate on the "event_key" field.
func EventKeyGTE(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldGTE(FieldEventKey, v))
}

// EventKeyLT applies the LT predicate on the "event_key" field.
func EventKeyLT(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldLT(FieldEventKey, v))
}

// EventKeyLTE applies the LTE predicate on the "event_key" field.
func EventKeyLTE(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldLTE(FieldEventKey, v))
}

// EventKeyContains applies the Contains predicate on the "event_key" field.
func EventKeyContains(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldContains(FieldEventKey, v))
}

// EventKeyHasPrefix applies the HasPrefix predicate on the "event_key" field.
func EventKeyHasPrefix(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldHasPrefix(FieldEventKey, v))
}

// EventKeyHasSuffix applies the HasSuffix predicate on the "event_key" field.
func EventKeyHasSuffix(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldHasSuffix(FieldEventKey, v))
}

// EventKeyEqualFold applies the EqualFold predicate on the "event_key" field.
func EventKeyEqualFold(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldEqualFold(FieldEventKey, v))
}

// EventKeyContainsFold applies the ContainsFold predicate on the "event_key" field.
func EventKeyContainsFold(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldContainsFold(FieldEventKey, v))
}

// StateBeforeEQ applies the EQ predicate on the "state_before" field.
func StateBeforeEQ(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldEQ(FieldStateBefore, v))
}

// StateBeforeNEQ applies the NEQ predicate on the "state_before" field.
func StateBeforeNEQ(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldNEQ(FieldStateBefore, v))
}

// StateBeforeIn applies the In predicate on the "state_before" field.
func StateBeforeIn(vs ...string) predicate.EventLog {
	return predicate.EventLog(sql.FieldIn(FieldStateBefore, vs...))
}

// StateBeforeNotIn applies the NotIn predicate on the "state_before" field.
func StateBeforeNotIn(vs ...string) predicate.EventLog {
	return predicate.EventLog(sql.FieldNotIn(FieldStateBefore, vs...))
}

// StateBeforeGT applies the GT predicate on the "state_before" field.
func StateBeforeGT(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldGT(FieldStateBefore, v))
}

// StateBeforeGTE applies the GTE predicate on the "state_before" field.
func StateBeforeGTE(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldGTE(FieldStateBefore, v))
}

// StateBeforeLT applies the LT predicate on the "state_before" field.
func StateBeforeLT(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldLT(FieldStateBefore, v))
}

// StateBeforeLTE applies the LTE predicate on the "state_before" field.
func StateBeforeLTE(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldLTE(FieldStateBefore, v))
}

// StateBeforeContains applies the Contains predicate on the "state_before" field.
func StateBeforeContains(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldContains(FieldStateBefore, v))
}

// StateBeforeHasPrefix applies the HasPrefix predicate on the "state_before" field.
func StateBeforeHasPrefix(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldHasPrefix(FieldStateBefore, v))
}

// StateBeforeHasSuffix applies the HasSuffix predicate on the "state_before" field.
func StateBeforeHasSuffix(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldHasSuffix(FieldStateBefore, v))
}

// StateBeforeEqualFold applies the EqualFold predicate on the "state_before" field.
func StateBeforeEqualFold(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldEqualFold(FieldStateBefore, v))
}

// StateBeforeContainsFold applies the ContainsFold predicate on the "state_before" field.
func StateBeforeContainsFold(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldContainsFold(FieldStateBefore, v))
}

// StateAfterEQ applies the EQ predicate on the "state_after" field.
func StateAfterEQ(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldEQ(FieldStateAfter, v))
}

// StateAfterNEQ applies the NEQ predicate on the "state_after" field.
func StateAfterNEQ(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldNEQ(FieldStateAfter, v))
}

// StateAfterIn applies the In predicate on the "state_after" field.
func StateAfterIn(vs ...string) predicate.EventLog {
	return predicate.EventLog(sql.FieldIn(FieldStateAfter, vs...))
}

// StateAfterNotIn applies the NotIn predicate on the "state_after" field.
func StateAfterNotIn(vs ...string) predicate.EventLog {
	return predicate.EventLog(sql.FieldNotIn(FieldStateAfter, vs...))
}

// StateAfterGT applies the GT predicate on the "state_after" field.
func StateAfterGT(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldGT(FieldStateAfter, v))
}

// StateAfterGTE applies the GTE predicate on the "state_after" field.
func StateAfterGTE(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldGTE(FieldStateAfter, v))
}

// StateAfterLT applies the LT predicate on the "state_after" field.
func StateAfterLT(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldLT(FieldStateAfter, v))
}

// StateAfterLTE applies the LTE predicate on the "state_after" field.
func StateAfterLTE(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldLTE(FieldStateAfter, v))
}

// StateAfterContains applies the Contains predicate on the "state_after" field.
func StateAfterContains(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldContains(FieldStateAfter, v))
}

// StateAfterHasPrefix applies the HasPrefix predicate on the "state_after" field.
func StateAfterHasPrefix(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldHasPrefix(FieldStateAfter, v))
}

// StateAfterHasSuffix applies the HasSuffix predicate on the "state_after" field.
func StateAfterHasSuffix(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldHasSuffix(FieldStateAfter, v))
}

// StateAfterEqualFold applies the EqualFold predicate on the "state_after" field.
func StateAfterEqualFold(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldEqualFold(FieldStateAfter, v))
}

// StateAfterContainsFold applies the ContainsFold predicate on the "state_after" field.
func StateAfterContainsFold(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldContainsFold(FieldStateAfter, v))
}

// ChangedAtEQ applies the EQ predicate on the "changed_at" field.
func ChangedAtEQ(v time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldEQ(FieldChangedAt, v))
}

// ChangedAtNEQ applies the NEQ predicate on the "changed_at" field.
func ChangedAtNEQ(v time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldNEQ(FieldChangedAt, v))
}

// ChangedAtIn applies the In predicate on the "changed_at" field.
func ChangedAtIn(vs ...time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldIn(FieldChangedAt, vs...))
}

// ChangedAtNotIn applies the NotIn predicate on the "changed_at" field.
func ChangedAtNotIn(vs ...time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldNotIn(FieldChangedAt, vs...))
}

// ChangedAtGT applies the GT predicate on the "changed_at" field.
func ChangedAtGT(v time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldGT(FieldChangedAt, v))
}

// ChangedAtGTE applies the GTE predicate on the "changed_at" field.
func ChangedAtGTE(v time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldGTE(FieldChangedAt, v))
}

// ChangedAtLT applies the LT predicate on the "changed_at" field.
func ChangedAtLT(v time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldLT(FieldChangedAt, v))
}

// ChangedAtLTE applies the LTE predicate on the "changed_at" field.
func ChangedAtLTE(v time.Time) predicate.EventLog {
	return predicate.EventLog(sql.FieldLTE(FieldChangedAt, v))
}

// ClientLogIDEQ applies the EQ predicate on the "client_log_id" field.
func ClientLogIDEQ(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldEQ(FieldClientLogID, v))
}

// ClientLogIDNEQ applies the NEQ predicate on the "client_log_id" field.
func ClientLogIDNEQ(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldNEQ(FieldClientLogID, v))
}

// ClientLogIDIn applies the In predicate on the "client_log_id" field.
func ClientLogIDIn(vs ...string) predicate.EventLog {
	return predicate.EventLog(sql.FieldIn(FieldClientLogID, vs...))
}

// ClientLogIDNotIn applies the NotIn predicate on the "client_log_id" field.
func ClientLogIDNotIn(vs ...string) predicate.EventLog {
	return predicate.EventLog(sql.FieldNotIn(FieldClientLogID, vs...))
}

// ClientLogIDGT applies the GT predicate on the "client_log_id" field.
func ClientLogIDGT(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldGT(FieldClientLogID, v))
}

// ClientLogIDGTE applies the GTE predicate on the "client_log_id" field.
func ClientLogIDGTE(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldGTE(FieldClientLogID, v))
}

// ClientLogIDLT applies the LT predicate on the "client_log_id" field.
func ClientLogIDLT(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldLT(FieldClientLogID, v))
}

// ClientLogIDLTE applies the LTE predicate on the "client_log_id" field.
func ClientLogIDLTE(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldLTE(FieldClientLogID, v))
}

// ClientLogIDContains applies the Contains predicate on the "client_log_id" field.
func ClientLogIDContains(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldContains(FieldClientLogID, v))
}

// ClientLogIDHasPrefix applies the HasPrefix predicate on the "client_log_id" field.
func ClientLogIDHasPrefix(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldHasPrefix(FieldClientLogID, v))
}

// ClientLogIDHasSuffix applies the HasSuffix predicate on the "client_log_id" field.
func ClientLogIDHasSuffix(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldHasSuffix(FieldClientLogID, v))
}

// ClientLogIDIsNil applies the IsNil predicate on the "client_log_id" field.
func ClientLogIDIsNil() predicate.EventLog {
	return predicate.EventLog(sql.FieldIsNull(FieldClientLogID))
}

// ClientLogIDNotNil applies the NotNil predicate on the "client_log_id" field.
func ClientLogIDNotNil() predicate.EventLog {
	return predicate.EventLog(sql.FieldNotNull(FieldClientLogID))
}

// ClientLogIDEqualFold applies the EqualFold predicate on the "client_log_id" field.
func ClientLogIDEqualFold(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldEqualFold(FieldClientLogID, v))
}

// ClientLogIDContainsFold applies the ContainsFold predicate on the "client_log_id" field.
func ClientLogIDContainsFold(v string) predicate.EventLog {
	return predicate.EventLog(sql.FieldContainsFold(FieldClientLogID, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.EventLog {
	return predicate.EventLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.EventLog {
	return predicate.EventLog(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EventLog) predicate.EventLog {
	return predicate.EventLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EventLog) predicate.EventLog {
	return predicate.EventLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EventLog) predicate.EventLog {
	return predicate.EventLog(sql.NotPredicates(p))
}
