// Code generated by ent, DO NOT EDIT.

package trank

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the trank type in the database.
	Label = "trank"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "Rank"
	// FieldCoefficient holds the string denoting the coefficient field in the database.
	FieldCoefficient = "coefficient"
	// Table holds the table name of the trank in the database.
	Table = "t_rank"
)

// Columns holds all SQL columns for trank fields.
var Columns = []string{
	FieldID,
	FieldCoefficient,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the TRank queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCoefficient orders the results by the coefficient field.
func ByCoefficient(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoefficient, opts...).ToFunc()
}
