// Code generated by ent, DO NOT EDIT.

package trank

import (
	"entgo.io/ent/dialect/sql"
	"github.com/witchs-lounge_backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.TRank {
	return predicate.TRank(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.TRank {
	return predicate.TRank(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.TRank {
	return predicate.TRank(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.TRank {
	return predicate.TRank(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.TRank {
	return predicate.TRank(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.TRank {
	return predicate.TRank(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.TRank {
	return predicate.TRank(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.TRank {
	return predicate.TRank(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.TRank {
	return predicate.TRank(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.TRank {
	return predicate.TRank(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.TRank {
	return predicate.TRank(sql.FieldContainsFold(FieldID, id))
}

// Coefficient applies equality check predicate on the "coefficient" field. It's identical to CoefficientEQ.
func Coefficient(v float32) predicate.TRank {
	return predicate.TRank(sql.FieldEQ(FieldCoefficient, v))
}

// CoefficientEQ applies the EQ predicate on the "coefficient" field.
func CoefficientEQ(v float32) predicate.TRank {
	return predicate.TRank(sql.FieldEQ(FieldCoefficient, v))
}

// CoefficientNEQ applies the NEQ predicate on the "coefficient" field.
func CoefficientNEQ(v float32) predicate.TRank {
	return predicate.TRank(sql.FieldNEQ(FieldCoefficient, v))
}

// CoefficientIn applies the In predicate on the "coefficient" field.
func CoefficientIn(vs ...float32) predicate.TRank {
	return predicate.TRank(sql.FieldIn(FieldCoefficient, vs...))
}

// CoefficientNotIn applies the NotIn predicate on the "coefficient" field.
func CoefficientNotIn(vs ...float32) predicate.TRank {
	return predicate.TRank(sql.FieldNotIn(FieldCoefficient, vs...))
}

// CoefficientGT applies the GT predicate on the "coefficient" field.
func CoefficientGT(v float32) predicate.TRank {
	return predicate.TRank(sql.FieldGT(FieldCoefficient, v))
}

// CoefficientGTE applies the GTE predicate on the "coefficient" field.
func CoefficientGTE(v float32) predicate.TRank {
	return predicate.TRank(sql.FieldGTE(FieldCoefficient, v))
}

// CoefficientLT applies the LT predicate on the "coefficient" field.
func CoefficientLT(v float32) predicate.TRank {
	return predicate.TRank(sql.FieldLT(FieldCoefficient, v))
}

// CoefficientLTE applies the LTE predicate on the "coefficient" field.
func CoefficientLTE(v float32) predicate.TRank {
	return predicate.TRank(sql.FieldLTE(FieldCoefficient, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TRank) predicate.TRank {
	return predicate.TRank(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TRank) predicate.TRank {
	return predicate.TRank(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TRank) predicate.TRank {
	return predicate.TRank(sql.NotPredicates(p))
}
