// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@witchslounge.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/musics": {
            "get": {
                "description": "활성화 된 악곡들을 가져옵니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Musics"
                ],
                "summary": "활성화 된 악곡들을 가져옵니다",
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/entity.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.MusicResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "서버 에러",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/musics/{music_id}/stages": {
            "get": {
                "description": "음악 id에 따른 스테이지들을 가져옵니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stages"
                ],
                "summary": "음악 id에 따른 스테이지들을 가져옵니다",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Music ID",
                        "name": "music_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/entity.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.StageResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "음악이 비활성화됨",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "서버 에러",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/records": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "해당 곡/스테이지의 전체 기록을 조회합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "summary": "전체 기록 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "음악 ID(UUID)",
                        "name": "music_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "스테이지 ID(UUID)",
                        "name": "stage_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "전체 기록",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/entity.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/repository.ListRecordResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "플레이 기록을 저장합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "summary": "플레이 기록 저장",
                "parameters": [
                    {
                        "description": "플레이 기록 요청",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.CreateRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "생성된 기록",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/entity.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/repository.SingleRecordResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "잘못된 요청 형식",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "인증 필요",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "서버 내부 오류",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/records/batch": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "오프라인 누적된 플레이 기록을 일괄 저장합니다 (멱등성: client_record_id)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "summary": "플레이 기록 일괄 저장",
                "parameters": [
                    {
                        "description": "batch 요청",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.BatchRecordsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "처리 결과",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/entity.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/repository.BatchRecordsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "잘못된 요청 형식 / 100건 초과",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "인증 필요",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "서버 내부 오류",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/records/best": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "해당 곡/스테이지의 최고 기록을 조회합니다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "summary": "최고 기록 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "음악 ID(UUID)",
                        "name": "music_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "스테이지 ID(UUID)",
                        "name": "stage_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "최고 기록",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/entity.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/repository.BestRecordResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/steam/signin": {
            "post": {
                "description": "Steam 티켓 인증을 통해 로그인 처리 및 세션 생성",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Steam"
                ],
                "summary": "Steam 로그인",
                "parameters": [
                    {
                        "description": "Steam 로그인 요청 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.SteamSignInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "로그인 성공 및 세션 정보",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/entity.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.SessionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "서버 내부 오류",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stove/signin": {
            "post": {
                "description": "Stove 액세스 토큰 검증 후 로그인 처리 및 세션 생성",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stove"
                ],
                "summary": "Stove 플랫폼으로 로그인",
                "parameters": [
                    {
                        "description": "Stove 로그인 요청 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.StoveSignInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "로그인 성공 및 세션 정보",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/entity.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.SessionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "요청 데이터 검증 실패",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "인증 실패",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "서버 내부 오류",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "세션 정보를 통해 현재 인증된 사용자의 상세 정보를 반환",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "현재 사용자 정보 조회",
                "responses": {
                    "200": {
                        "description": "사용자 정보",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/entity.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "인증 정보 없음",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "서버 내부 오류",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.MusicResponse": {
            "type": "object",
            "properties": {
                "artist": {
                    "type": "string"
                },
                "bpm": {
                    "type": "number"
                },
                "composer": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "genre": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_free": {
                    "type": "boolean"
                },
                "is_recommended": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "release_date": {
                    "type": "string"
                },
                "unlock_level": {
                    "type": "integer"
                }
            }
        },
        "dto.StageResponse": {
            "type": "object",
            "properties": {
                "difficulty": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "level_name": {
                    "type": "string"
                },
                "max_combo": {
                    "type": "integer"
                },
                "music_id": {
                    "type": "string"
                },
                "total_notes": {
                    "type": "integer"
                }
            }
        },
        "entity.BatchRecordItem": {
            "type": "object",
            "required": [
                "client_record_id",
                "music_id",
                "score",
                "stage_id"
            ],
            "properties": {
                "accuracy": {
                    "type": "number"
                },
                "additional_info": {
                    "type": "object",
                    "additionalProperties": true
                },
                "bad_count": {
                    "type": "integer"
                },
                "client_record_id": {
                    "type": "string"
                },
                "game_status": {
                    "type": "string",
                    "enum": [
                        "completed",
                        "gave_up",
                        "retry",
                        "failed"
                    ]
                },
                "good_count": {
                    "type": "integer"
                },
                "is_full_combo": {
                    "type": "boolean"
                },
                "is_perfect_play": {
                    "type": "boolean"
                },
                "max_combo": {
                    "type": "integer"
                },
                "miss_count": {
                    "type": "integer"
                },
                "music_id": {
                    "type": "string"
                },
                "perfect_count": {
                    "type": "integer"
                },
                "play_duration": {
                    "type": "number"
                },
                "rank": {
                    "type": "string"
                },
                "score": {
                    "type": "integer",
                    "minimum": 0
                },
                "stage_id": {
                    "type": "string"
                }
            }
        },
        "entity.BatchRecordsRequest": {
            "type": "object",
            "required": [
                "records"
            ],
            "properties": {
                "records": {
                    "type": "array",
                    "maxItems": 100,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/entity.BatchRecordItem"
                    }
                }
            }
        },
        "entity.CreateRecordRequest": {
            "type": "object",
            "required": [
                "music_id",
                "score",
                "stage_id"
            ],
            "properties": {
                "accuracy": {
                    "type": "number"
                },
                "additional_info": {
                    "type": "object",
                    "additionalProperties": true
                },
                "bad_count": {
                    "type": "integer"
                },
                "game_status": {
                    "type": "string",
                    "enum": [
                        "completed",
                        "gave_up",
                        "retry",
                        "failed"
                    ]
                },
                "good_count": {
                    "type": "integer"
                },
                "is_full_combo": {
                    "type": "boolean"
                },
                "is_perfect_play": {
                    "type": "boolean"
                },
                "max_combo": {
                    "type": "integer"
                },
                "miss_count": {
                    "type": "integer"
                },
                "music_id": {
                    "type": "string"
                },
                "perfect_count": {
                    "type": "integer"
                },
                "play_duration": {
                    "type": "number"
                },
                "rank": {
                    "type": "string"
                },
                "score": {
                    "type": "integer",
                    "minimum": 0
                },
                "stage_id": {
                    "type": "string"
                }
            }
        },
        "entity.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {},
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "entity.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "entity.SessionResponse": {
            "type": "object",
            "properties": {
                "hmac_secret": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/entity.UserResponse"
                }
            }
        },
        "entity.SteamSignInRequest": {
            "type": "object",
            "required": [
                "id",
                "ticket"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "ticket": {
                    "type": "string"
                }
            }
        },
        "entity.StoveSignInRequest": {
            "type": "object",
            "required": [
                "access_token"
            ],
            "properties": {
                "access_token": {
                    "type": "string"
                }
            }
        },
        "entity.UserResponse": {
            "type": "object",
            "properties": {
                "coin": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "exp": {
                    "type": "integer"
                },
                "gem": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "is_verified": {
                    "type": "boolean"
                },
                "language": {
                    "type": "string"
                },
                "level": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "platform_avatar_url": {
                    "type": "string"
                },
                "platform_display_name": {
                    "type": "string"
                },
                "platform_email": {
                    "type": "string"
                },
                "platform_type": {
                    "type": "string"
                },
                "platform_user_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "repository.BatchItemStatus": {
            "type": "string",
            "enum": [
                "accepted",
                "duplicate",
                "rejected"
            ],
            "x-enum-varnames": [
                "BatchStatusAccepted",
                "BatchStatusDuplicate",
                "BatchStatusRejected"
            ]
        },
        "repository.BatchRecordsResponse": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/repository.BatchResultItem"
                    }
                },
                "user_after": {
                    "$ref": "#/definitions/repository.BatchUserAfter"
                }
            }
        },
        "repository.BatchRejectReason": {
            "type": "string",
            "enum": [
                "invalid_payload",
                "unknown_music",
                "unknown_stage",
                "score_out_of_range",
                "payload_inconsistent",
                "duration_out_of_range"
            ],
            "x-enum-varnames": [
                "ReasonInvalidPayload",
                "ReasonUnknownMusic",
                "ReasonUnknownStage",
                "ReasonScoreOutOfRange",
                "ReasonPayloadInconsistent",
                "ReasonDurationOutOfRange"
            ]
        },
        "repository.BatchResultItem": {
            "type": "object",
            "properties": {
                "client_record_id": {
                    "type": "string"
                },
                "exp_gain": {
                    "$ref": "#/definitions/repository.ExpGain"
                },
                "reason": {
                    "$ref": "#/definitions/repository.BatchRejectReason"
                },
                "record_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/repository.BatchItemStatus"
                }
            }
        },
        "repository.BatchUserAfter": {
            "type": "object",
            "properties": {
                "exp": {
                    "type": "integer"
                },
                "level": {
                    "type": "integer"
                }
            }
        },
        "repository.BestRecordResponse": {
            "type": "object",
            "properties": {
                "record": {
                    "$ref": "#/definitions/repository.RecordResponse"
                }
            }
        },
        "repository.ExpGain": {
            "type": "object",
            "properties": {
                "exp_from": {
                    "type": "integer"
                },
                "exp_gained": {
                    "type": "integer"
                },
                "exp_to": {
                    "type": "integer"
                },
                "level_from": {
                    "type": "integer"
                },
                "level_to": {
                    "type": "integer"
                }
            }
        },
        "repository.ListRecordResponse": {
            "type": "object",
            "properties": {
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/repository.RecordResponse"
                    }
                }
            }
        },
        "repository.RecordResponse": {
            "type": "object",
            "properties": {
                "accuracy": {
                    "type": "number"
                },
                "additional_info": {
                    "type": "object",
                    "additionalProperties": true
                },
                "bad_count": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "good_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "is_full_combo": {
                    "type": "boolean"
                },
                "is_perfect_play": {
                    "type": "boolean"
                },
                "max_combo": {
                    "type": "integer"
                },
                "miss_count": {
                    "type": "integer"
                },
                "music_id": {
                    "type": "string"
                },
                "perfect_count": {
                    "type": "integer"
                },
                "rank": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "stage_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "repository.SingleRecordResponse": {
            "type": "object",
            "properties": {
                "exp_gain": {
                    "$ref": "#/definitions/repository.ExpGain"
                },
                "record": {
                    "$ref": "#/definitions/repository.RecordResponse"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Witch's Lounge API",
	Description:      "Witch's Lounge Backend API Server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
